// ==========================================
// IELTS VOCAB DATA - UPDATED WITH NESTED PASSAGES
// ==========================================
// Cập nhật từ vựng ở file này, không cần động vào index.html

const VOCAB_DATA = {
    reading: {
        1: {
            inclass: {
                "Acknowledge": { ipa: "/əkˈnɒl.ɪdʒ/", meaning: "Thừa nhận, công nhận", paraphrase: "He finally had to <strong>acknowledge</strong> that he was wrong about the project timeline.", type: "verb" },
                "Aggregate": { ipa: "/ˈæɡ.rɪ.ɡət/", meaning: "Tổng hợp, kết hợp", paraphrase: "The report presents an <strong>aggregate</strong> of all the survey data collected over six months.", type: "noun/verb" },
                "Allocate": { ipa: "/ˈæl.ə.keɪt/", meaning: "Phân bổ", paraphrase: "The committee decided to <strong>allocate</strong> more funds to the environmental protection program.", type: "verb" },
                "Ambiguous": { ipa: "/æmˈbɪɡ.ju.əs/", meaning: "Mơ hồ, lưỡng nghĩa", paraphrase: "Her response was deliberately <strong>ambiguous</strong>, leaving everyone unsure of her true intentions.", type: "adjective" },
                "Amend": { ipa: "/əˈmend/", meaning: "Sửa đổi, cải thiện", paraphrase: "The parliament voted to <strong>amend</strong> the constitution to include new civil rights protections.", type: "verb" },
                "Analogy": { ipa: "/əˈnæl.ə.dʒi/", meaning: "Sự tương tự", paraphrase: "The teacher used the <strong>analogy</strong> of a tree's roots to explain how family history shapes us.", type: "noun" },
                "Arbitrary": { ipa: "/ˈɑː.bɪ.trər.i/", meaning: "Tùy tiện, độc đoán", paraphrase: "The manager's <strong>arbitrary</strong> decision to change the deadline caused widespread frustration.", type: "adjective" },
                "Assemble": { ipa: "/əˈsem.bəl/", meaning: "Tập hợp, lắp ráp", paraphrase: "It took us three hours to <strong>assemble</strong> the complicated bookshelf from the flat-pack box.", type: "verb" },
                "Attain": { ipa: "/əˈteɪn/", meaning: "Đạt được", paraphrase: "After years of hard work, she finally <strong>attained</strong> her goal of becoming a published author.", type: "verb" },
                "Attribute": { ipa: "/əˈtrɪb.juːt/", meaning: "Thuộc tính, quy cho", paraphrase: "Many historians <strong>attribute</strong> the company's success to its innovative marketing strategy.", type: "noun/verb" },
                "Bias": { ipa: "/ˈbaɪ.əs/", meaning: "Thành kiến, thiên vị", paraphrase: "The study was criticized for having a clear <strong>bias</strong> toward confirming the researcher's hypothesis.", type: "noun" },
                "Bulk": { ipa: "/bʌlk/", meaning: "Phần lớn, số lượng lớn", paraphrase: "The <strong>bulk</strong> of the work was completed during the first week of the project.", type: "noun" },
                "Coherent": { ipa: "/kəʊˈhɪə.rənt/", meaning: "Mạch lạc, chặt chẽ", paraphrase: "Despite the pressure, she gave a remarkably <strong>coherent</strong> presentation to the board of directors.", type: "adjective" },
                "Coincide": { ipa: "/ˌkəʊ.ɪnˈsaɪd/", meaning: "Trùng hợp", paraphrase: "Her graduation ceremony will <strong>coincide</strong> with her parents' 30th wedding anniversary.", type: "verb" },
                "Commodity": { ipa: "/kəˈmɒd.ə.ti/", meaning: "Hàng hóa", paraphrase: "Coffee has become a global <strong>commodity</strong> traded on international markets.", type: "noun" },
                "Compatible": { ipa: "/kəmˈpæt.ə.bəl/", meaning: "Tương thích", paraphrase: "Make sure the software is <strong>compatible</strong> with your operating system before purchasing.", type: "adjective" },
                "Compile": { ipa: "/kəmˈpaɪl/", meaning: "Biên soạn, thu thập", paraphrase: "The editor spent months <strong>compiling</strong> articles from various experts for the anthology.", type: "verb" },
                "Complement": { ipa: "/ˈkɒm.plɪ.ment/", meaning: "Bổ sung", paraphrase: "The white wine perfectly <strong>complemented</strong> the delicate flavors of the fish dish.", type: "noun/verb" },
                "Conceive": { ipa: "/kənˈsiːv/", meaning: "Hình thành trong đầu", paraphrase: "The architect <strong>conceived</strong> the building's unique design while traveling in Japan.", type: "verb" },
                "Concurrent": { ipa: "/kənˈkʌr.ənt/", meaning: "Đồng thời", paraphrase: "The company is running three <strong>concurrent</strong> marketing campaigns in different regions.", type: "adjective" }
            },
            homework: {}
        },
        2: { 
            inclass: {}, 
            homework: {
                "petition": { ipa: "/pəˈtɪʃ.ən/", meaning: "đơn kiến nghị", paraphrase: "More than 50,000 people signed the <strong>petition</strong> to save the local library from closure.", type: "noun" },
                "discontent": { ipa: "/ˌdɪs.kənˈtent/", meaning: "sự bất mãn", paraphrase: "There was growing <strong>discontent</strong> among employees about the new overtime policy.", type: "noun" },
                "social unrest": { ipa: "/ˌsəʊ.ʃəl ʌnˈrest/", meaning: "bất ổn xã hội", paraphrase: "The government's economic policies led to widespread <strong>social unrest</strong> across the country.", type: "noun phrase" },
                "appalling": { ipa: "/əˈpɔː.lɪŋ/", meaning: "kinh khủng", paraphrase: "The conditions in the refugee camp were absolutely <strong>appalling</strong> and inhumane.", type: "adjective" },
                "suffrage": { ipa: "/ˈsʌf.rɪdʒ/", meaning: "quyền bầu cử", paraphrase: "The women's <strong>suffrage</strong> movement fought for decades to secure voting rights.", type: "noun" },
                "trade union": { ipa: "/ˌtreɪd ˈjuː.njən/", meaning: "công đoàn", paraphrase: "The <strong>trade union</strong> negotiated better working conditions for all factory employees.", type: "noun phrase" },
                "collapse": { ipa: "/kəˈlæps/", meaning: "sụp đổ", paraphrase: "The old building could <strong>collapse</strong> at any moment due to structural damage.", type: "verb" },
                "subsequent": { ipa: "/ˈsʌb.sɪ.kwənt/", meaning: "tiếp theo", paraphrase: "The initial failure was followed by <strong>subsequent</strong> attempts that eventually succeeded.", type: "adjective" },
                "disillusionment": { ipa: "/ˌdɪs.ɪˈluː.ʒən.mənt/", meaning: "vỡ mộng", paraphrase: "Many voters felt a deep sense of <strong>disillusionment</strong> after the election promises were broken.", type: "noun" },
                "found": { ipa: "/faʊnd/", meaning: "thành lập", paraphrase: "The university was <strong>found</strong> in 1850 with just 35 students and three professors.", type: "verb" },
                "reform parliament": { ipa: "/rɪˈfɔːm ˈpɑː.lɪə.mənt/", meaning: "quốc hội cải cách", paraphrase: "The activists demanded a <strong>reform parliament</strong> that would represent ordinary citizens better.", type: "noun phrase" },
                "champion": { ipa: "/ˈtʃæm.pi.ən/", meaning: "ủng hộ, bảo vệ", paraphrase: "She continues to <strong>champion</strong> environmental causes despite political opposition.", type: "verb" },
                "key figure": { ipa: "/kiː ˈfɪɡ.ər/", meaning: "nhân vật chủ chốt", paraphrase: "Martin Luther King Jr. was a <strong>key figure</strong> in the American civil rights movement.", type: "noun phrase" },
                "delegate": { ipa: "/ˈdel.ɪ.ɡət/", meaning: "đại biểu", paraphrase: "Each country sent a <strong>delegate</strong> to the international climate conference.", type: "noun" },
                "proclaim": { ipa: "/prəˈkleɪm/", meaning: "tuyên bố", paraphrase: "The king <strong>proclaimed</strong> a national holiday to celebrate the victory.", type: "verb" },
                "sacred": { ipa: "/ˈseɪ.krɪd/", meaning: "thiêng liêng", paraphrase: "The temple is considered a <strong>sacred</strong> place where visitors must remove their shoes.", type: "adjective" },
                "dismiss": { ipa: "/dɪsˈmɪs/", meaning: "bác bỏ", paraphrase: "The judge decided to <strong>dismiss</strong> the case due to lack of evidence.", type: "verb" },
                "troops": { ipa: "/truːps/", meaning: "quân đội", paraphrase: "The government sent <strong>troops</strong> to help with disaster relief after the earthquake.", type: "noun" },
                "miner": { ipa: "/ˈmaɪ.nər/", meaning: "thợ mỏ", paraphrase: "The <strong>miner</strong> spent eight hours each day extracting coal deep underground.", type: "noun" },
                "crush": { ipa: "/krʌʃ/", meaning: "đàn áp", paraphrase: "The military government attempted to <strong>crush</strong> the protest movement with violent force.", type: "verb" },
                "riot": { ipa: "/ˈraɪ.ət/", meaning: "bạo loạn", paraphrase: "The football match ended in a <strong>riot</strong> when fans began fighting in the stadium.", type: "noun" },
                "abandon": { ipa: "/əˈbæn.dən/", meaning: "từ bỏ", paraphrase: "They had to <strong>abandon</strong> their car when it broke down in the middle of nowhere.", type: "verb" },
                "the cause": { ipa: "/ðə kɔːz/", meaning: "sự nghiệp", paraphrase: "She dedicated her life to <strong>the cause</strong> of education for underprivileged children.", type: "noun phrase" },
                "prominence": { ipa: "/ˈprɒm.ɪ.nəns/", meaning: "nổi bật", paraphrase: "The young artist rose to <strong>prominence</strong> after winning an international competition.", type: "noun" },
                "procession": { ipa: "/prəˈseʃ.ən/", meaning: "diễu hành", paraphrase: "A solemn <strong>procession</strong> of mourners followed the funeral carriage through the town.", type: "noun" },
                "take precaution": { ipa: "/teɪk prɪˈkɔː.ʃən/", meaning: "đề phòng", paraphrase: "Always <strong>take precautions</strong> when hiking in remote mountain areas.", type: "verb phrase" },
                "discredit": { ipa: "/dɪˈskred.ɪt/", meaning: "làm mất uy tín", paraphrase: "The opposition party tried to <strong>discredit</strong> the minister with false accusations.", type: "verb" },
                "fiasco": { ipa: "/fiˈæs.kəʊ/", meaning: "thất bại thảm hại", paraphrase: "The product launch turned into a complete <strong>fiasco</strong> when the demonstration failed.", type: "noun" },
                "abolition": { ipa: "/ˌæb.əˈlɪʃ.ən/", meaning: "bãi bỏ", paraphrase: "The <strong>abolition</strong> of slavery was a major milestone in human rights history.", type: "noun" },
                "far ahead of the times": { ipa: "/fɑːr əˈhed əv ðə taɪmz/", meaning: "vượt thời đại", paraphrase: "Da Vinci's inventions were <strong>far ahead of the times</strong> and not understood until centuries later.", type: "phrase" },
                "resolute action": { ipa: "/ˈrez.ə.luːt ˈæk.ʃən/", meaning: "hành động kiên quyết", paraphrase: "The crisis required immediate and <strong>resolute action</strong> from the emergency services.", type: "noun phrase" },
                "suppress": { ipa: "/səˈpres/", meaning: "đàn áp", paraphrase: "The regime tried to <strong>suppress</strong> all news about the protest from reaching international media.", type: "verb" },
                "rejection": { ipa: "/rɪˈdʒek.ʃən/", meaning: "từ chối", paraphrase: "She handled the job <strong>rejection</strong> professionally and asked for feedback to improve.", type: "noun" },
                "radical": { ipa: "/ˈræd.ɪ.kəl/", meaning: "cấp tiến", paraphrase: "The party proposed <strong>radical</strong> changes to the healthcare system that divided public opinion.", type: "adjective" },
                "austerity measures": { ipa: "/ɔːˈster.ə.ti ˈmeʒ.əz/", meaning: "thắt lưng buộc bụng", paraphrase: "The government introduced harsh <strong>austerity measures</strong> to reduce the national debt.", type: "noun phrase" },
                "slash": { ipa: "/slæʃ/", meaning: "cắt giảm", paraphrase: "The company announced it would <strong>slash</strong> 500 jobs to cut costs.", type: "verb" },
                "hike tax": { ipa: "/haɪk tæks/", meaning: "tăng thuế", paraphrase: "The government plans to <strong>hike taxes</strong> on luxury goods to fund public services.", type: "verb phrase" },
                "impose": { ipa: "/ɪmˈpəʊz/", meaning: "áp đặt", paraphrase: "The school decided to <strong>impose</strong> a strict uniform policy starting next semester.", type: "verb" },
                "deficit": { ipa: "/ˈdef.ɪ.sɪt/", meaning: "thâm hụt", paraphrase: "The country's trade <strong>deficit</strong> widened significantly last quarter.", type: "noun" },
                "unsustainable": { ipa: "/ˌʌn.səsˈteɪ.nə.bəl/", meaning: "không bền vững", paraphrase: "Current levels of plastic consumption are completely <strong>unsustainable</strong> for the planet.", type: "adjective" },
                "roll over current loans": { ipa: "/rəʊl ˈəʊ.vər ˈkʌr.ənt ləʊnz/", meaning: "gia hạn vay", paraphrase: "The bank agreed to <strong>roll over the current loans</strong> for another six months.", type: "verb phrase" },
                "interest rate": { ipa: "/ˈɪn.trəst reɪt/", meaning: "lãi suất", paraphrase: "The central bank raised the <strong>interest rate</strong> to control inflation.", type: "noun phrase" },
                "curtail": { ipa: "/kɜːˈteɪl/", meaning: "cắt giảm", paraphrase: "The airline had to <strong>curtail</strong> its services during the pandemic.", type: "verb" },
                "elevate": { ipa: "/ˈel.ɪ.veɪt/", meaning: "nâng cao", paraphrase: "The new program aims to <strong>elevate</strong> the standard of teaching in rural schools.", type: "verb" },
                "excise": { ipa: "/ˈek.saɪz/", meaning: "thuế tiêu thụ", paraphrase: "The government increased the <strong>excise</strong> on tobacco products to discourage smoking.", type: "noun" },
                "narrow": { ipa: "/ˈnær.əʊ/", meaning: "thu hẹp", paraphrase: "The gap between rich and poor continues to <strong>narrow</strong> in some developing countries.", type: "verb" },
                "allowance": { ipa: "/əˈlaʊ.əns/", meaning: "phụ cấp", paraphrase: "Students receive a monthly <strong>allowance</strong> to cover living expenses.", type: "noun" },
                "succession": { ipa: "/səkˈseʃ.ən/", meaning: "kế tiếp", paraphrase: "The company experienced a <strong>succession</strong> of leadership changes in just two years.", type: "noun" },
                "indict": { ipa: "/ɪnˈdaɪt/", meaning: "truy tố", paraphrase: "The grand jury decided to <strong>indict</strong> the former executive on fraud charges.", type: "verb" },
                "crisis": { ipa: "/ˈkraɪ.sɪs/", meaning: "khủng hoảng", paraphrase: "The economic <strong>crisis</strong> left millions of people unemployed.", type: "noun" },
                "soar": { ipa: "/sɔːr/", meaning: "tăng vọt", paraphrase: "Temperatures are expected to <strong>soar</strong> above 40 degrees Celsius this weekend.", type: "verb" },
                "turn sour": { ipa: "/tɜːn ˈsaʊər/", meaning: "trở nên xấu", paraphrase: "Their business partnership began to <strong>turn sour</strong> after financial disagreements.", type: "verb phrase" },
                "retract": { ipa: "/rɪˈtrækt/", meaning: "rút lại", paraphrase: "The newspaper had to <strong>retract</strong> the article after discovering factual errors.", type: "verb" },
                "decimate": { ipa: "/ˈdes.ɪ.meɪt/", meaning: "tàn phá", paraphrase: "The hurricane is expected to <strong>decimate</strong> coastal communities along its path.", type: "verb" },
                "out of work": { ipa: "/aʊt əv wɜːk/", meaning: "thất nghiệp", paraphrase: "Many factory workers found themselves <strong>out of work</strong> after the plant closure.", type: "adjective phrase" },
                "implement": { ipa: "/ˈɪm.plɪ.ment/", meaning: "thực thi", paraphrase: "It will take months to fully <strong>implement</strong> the new safety regulations.", type: "verb" },
                "slump": { ipa: "/slʌmp/", meaning: "sụt giảm", paraphrase: "The housing market experienced a severe <strong>slump</strong> during the recession.", type: "noun" },
                "denounce": { ipa: "/dɪˈnaʊns/", meaning: "lên án", paraphrase: "Human rights organizations <strong>denounced</strong> the government's violent crackdown on protests.", type: "verb" },
                "frivolity": { ipa: "/frɪˈvɒl.ə.ti/", meaning: "phù phiếm", paraphrase: "Some critics dismissed the art exhibition as mere <strong>frivolity</strong> without deeper meaning.", type: "noun" },
                "ratchet up": { ipa: "/ˈrætʃ.ɪt ʌp/", meaning: "tăng dần", paraphrase: "Both countries continued to <strong>ratchet up</strong> their military presence along the border.", type: "verb phrase" },
                "contract": { ipa: "/kənˈtrækt/", meaning: "co lại", paraphrase: "Muscles naturally <strong>contract</strong> and relax during exercise.", type: "verb" }
            }
        },
        3: { 
            inclass: {}, 
            homework: {
                "Three dimensional film": {
                    "commercial debut": { ipa: "/kəˈmɜː.ʃəl ˈdeɪ.bjuː/", meaning: "Công chiếu thương mại", paraphrase: "The film made its <strong>commercial debut</strong> in Los Angeles in 1922.", type: "noun phrase", paragraph: "A" },
                    "subsequently": { ipa: "/ˈsʌb.sɪ.kwənt.li/", meaning: "Về sau", paraphrase: "The film was shown in New York but <strong>subsequently</strong> not picked up for distribution.", type: "adverb", paragraph: "A" },
                    "pioneers": { ipa: "/ˌpaɪəˈnɪərz/", meaning: "Những người tiên phong", paraphrase: "The following decades were a period of quiet experimentation for 3-D <strong>pioneers</strong>.", type: "noun", paragraph: "A" },
                    "wax": { ipa: "/wæks/", meaning: "Tăng lên, phát triển", paraphrase: "3-D technology <strong>waxed</strong> and waned within filmmaking circles over the decades.", type: "verb", paragraph: "A" },
                    "wane": { ipa: "/weɪn/", meaning: "Suy giảm", paraphrase: "The popularity of 3-D <strong>waned</strong> after its initial success.", type: "verb", paragraph: "A" },
                    "blockbuster": { ipa: "/ˈblɒkˌbʌs.tər/", meaning: "Phim bom tấn", paraphrase: "Avatar cemented 3-D as a production tool for <strong>blockbuster</strong> films.", type: "noun", paragraph: "B" },
                    "novelty": { ipa: "/ˈnɒv.əl.ti/", meaning: "Sự mới lạ", paraphrase: "3-D is no longer a mere niche or <strong>novelty</strong> experiment.", type: "noun", paragraph: "B" },
                    "behemoth": { ipa: "/bɪˈhiː.mɒθ/", meaning: "Vật to lớn khổng lồ", paraphrase: "Avatar was described as 'The <strong>behemoth</strong>... the holy grail of 3-D'.", type: "noun", paragraph: "B" },
                    "spice up": { ipa: "/spaɪs ʌp/", meaning: "Làm thú vị hơn", paraphrase: "3-D <strong>spices up</strong> a trip to the cinema by adding an active layer of experience.", type: "phrasal verb", paragraph: "C" },
                    "gimmick": { ipa: "/ˈɡɪm.ɪk/", meaning: "Mánh khóe, chiêu trò", paraphrase: "New technology is frequently seen as a <strong>gimmick</strong> in its early days.", type: "noun", paragraph: "C" },
                    "greet with open arms": { ipa: "/ɡriːt wɪð ˈəʊ.pən ɑːmz/", meaning: "Đón chào nồng nhiệt", paraphrase: "Not everyone <strong>greets</strong> the rise of 3-D <strong>with open arms</strong>.", type: "phrase", paragraph: "D" },
                    "conjure": { ipa: "/ˈkʌn.dʒər/", meaning: "Gợi lên, tạo ra", paraphrase: "The perception of depth <strong>conjured</strong> through 3-D does not complement natural angles.", type: "verb", paragraph: "D" },
                    "complement": { ipa: "/ˈkɒm.plɪ.ment/", meaning: "Bổ sung, hoàn thiện", paraphrase: "3-D effects do not <strong>complement</strong> the angles from which we view the world.", type: "verb", paragraph: "D" },
                    "nausea": { ipa: "/ˈnɔː.zi.ə/", meaning: "Buồn nôn", paraphrase: "Eyestrains, headaches and <strong>nausea</strong> affect around 15% of 3-D film audiences.", type: "noun", paragraph: "D" },
                    "detrimental": { ipa: "/ˌdet.rɪˈmen.təl/", meaning: "Có hại", paraphrase: "Film critic Roger Ebert warns that 3-D is <strong>detrimental</strong> to good film-making.", type: "adjective", paragraph: "E" },
                    "contrived": { ipa: "/kənˈtraɪvd/", meaning: "Gượng ép, giả tạo", paraphrase: "The overall effect of 3-D can seem clumsy and <strong>contrived</strong>.", type: "adjective", paragraph: "E" },
                    "over-hyped": { ipa: "/ˌəʊ.vərˈhaɪpt/", meaning: "Được thổi phồng quá mức", paraphrase: "3-D may go down in history as an <strong>over-hyped</strong>, expensive novelty.", type: "adjective", paragraph: "F" }
                },
                "MUSIC": {
                    "disorder": { ipa: "/dɪˈsɔː.dər/", meaning: "Hỗn loạn, vô trật tự", paraphrase: "Did music's ability to express emotions create potential for <strong>disorder</strong>?", type: "noun", paragraph: "A" },
                    "come clean": { ipa: "/kʌm kliːn/", meaning: "Thú nhận, nói thẳng", paraphrase: "Shakespeare <strong>came clean</strong> about his views on music.", type: "phrase", paragraph: "B" },
                    "hath": { ipa: "/hæθ/", meaning: "Có (cổ ngữ)", paraphrase: "'The man who <strong>hath</strong> no music in himself...' (Shakespeare)", type: "verb", paragraph: "B" },
                    "concord": { ipa: "/ˈkɒŋ.kɔːd/", meaning: "Hòa hợp, đồng thuận", paraphrase: "Nor is not mov'd with <strong>concord</strong> of sweet sounds.", type: "noun", paragraph: "B" },
                    "treason": { ipa: "/ˈtriː.zən/", meaning: "Tội phản bội", paraphrase: "Is fit for <strong>treasons</strong>, strategems and spoils.", type: "noun", paragraph: "B" },
                    "whole": { ipa: "/həʊl/", meaning: "Toàn vẹn, nguyên vẹn", paraphrase: "Music as a healing force that makes man <strong>whole</strong>.", type: "adjective", paragraph: "B" },
                    "therapy": { ipa: "/ˈθer.ə.pi/", meaning: "Liệu pháp", paraphrase: "The growth of the science of music <strong>therapy</strong> within the last two centuries.", type: "noun", paragraph: "C" },
                    "anecdotal": { ipa: "/ˌæn.ɪkˈdəʊ.təl/", meaning: "Giai thoại, không chính thức", paraphrase: "The 'Mozart effect' presents <strong>anecdotal</strong> and statistical evidence.", type: "adjective", paragraph: "C" },
                    "formative": { ipa: "/ˈfɔː.mə.tɪv/", meaning: "Hình thành, phát triển", paraphrase: "Children exposed in their <strong>formative</strong> years to music.", type: "adjective", paragraph: "C" },
                    "obsessed": { ipa: "/əbˈsest/", meaning: "Ám ảnh", paraphrase: "In an age <strong>obsessed</strong> by pragmatism and short-term learning.", type: "adjective", paragraph: "C" },
                    "vocational": { ipa: "/vəʊˈkeɪ.ʃən.əl/", meaning: "Thuộc về nghề nghiệp", paraphrase: "Short-term <strong>vocational</strong> learning has marginalized music.", type: "adjective", paragraph: "C" },
                    "marginalize": { ipa: "/ˈmɑː.dʒɪ.nəl.aɪz/", meaning: "Gạt ra bên lề", paraphrase: "Music has been <strong>marginalized</strong> in primary and secondary education.", type: "verb", paragraph: "C" },
                    "luxury": { ipa: "/ˈlʌk.ʃər.i/", meaning: "Xa xỉ, không cần thiết", paraphrase: "Music is regarded as a <strong>luxury</strong> pastime compared to core subjects.", type: "noun", paragraph: "C" },
                    "heritage": { ipa: "/ˈher.ɪ.tɪdʒ/", meaning: "Di sản, truyền thống", paraphrase: "Children are leaving school ignorant of their musical <strong>heritage</strong>.", type: "noun", paragraph: "C" },
                    "plethora": { ipa: "/ˈpleθ.ər.ə/", meaning: "Quá nhiều, dư thừa", paraphrase: "Playing an instrument requires a <strong>plethora</strong> of mental and physical skills.", type: "noun", paragraph: "D" },
                    "erode": { ipa: "/ɪˈrəʊd/", meaning: "Xói mòn, làm suy yếu", paraphrase: "Skills which are being <strong>eroded</strong> in our push-button world.", type: "verb", paragraph: "D" },
                    "respiratory": { ipa: "/rəˈspɪr.ə.tər.i/", meaning: "Thuộc về hô hấp", paraphrase: "Wind instruments help overcome upper and lower <strong>respiratory</strong> tract problems.", type: "adjective", paragraph: "E" },
                    "abdominal": { ipa: "/æbˈdɒm.ɪ.nəl/", meaning: "Thuộc về bụng", paraphrase: "<strong>Abdominal</strong> muscles are used to support the breathing system.", type: "adjective", paragraph: "E" },
                    "muscles": { ipa: "/ˈmʌs.əlz/", meaning: "Cơ bắp", paraphrase: "These are the very <strong>muscles</strong> used when playing wind instruments.", type: "noun", paragraph: "E" },
                    "primitive": { ipa: "/ˈprɪm.ɪ.tɪv/", meaning: "Nguyên thủy, sơ khai", paraphrase: "The human being's most <strong>primitive</strong> form of music-making is singing.", type: "adjective", paragraph: "F" },
                    "yet": { ipa: "/jet/", meaning: "Nhưng, tuy nhiên", paraphrase: "A simple <strong>yet</strong> comprehensive system of body language.", type: "conjunction", paragraph: "G" },
                    "adapt": { ipa: "/əˈdæpt/", meaning: "Thích nghi, điều chỉnh", paraphrase: "The Voices Foundation <strong>adapts</strong> and applies Kodaly's methods.", type: "verb", paragraph: "G" },
                    "breadth": { ipa: "/bredθ/", meaning: "Chiều rộng, phạm vi", paraphrase: "Achieved extraordinary effects the length and <strong>breadth</strong> of Britain.", type: "noun", paragraph: "G" },
                    "womb": { ipa: "/wuːm/", meaning: "Tử cung", paraphrase: "Music in the <strong>womb</strong> is part of the life of unborn Finnish children.", type: "noun", paragraph: "H" },
                    "educational": { ipa: "/ˌed.jʊˈkeɪ.ʃən.əl/", meaning: "Thuộc về giáo dục", paraphrase: "Look at the <strong>educational</strong> standards and health records in Finland.", type: "adjective", paragraph: "H" },
                    "standard": { ipa: "/ˈstæn.dəd/", meaning: "Tiêu chuẩn, mức độ", paraphrase: "High educational <strong>standards</strong> in Finland show the benefits of music.", type: "noun", paragraph: "H" }
                }
            }
        },
        4: { inclass: {}, homework: {} },
        5: { inclass: {}, homework: {} },
        6: { inclass: {}, homework: {} },
        7: { 
            inclass: {},
            homework: {
                "Professional Strangers": {
                    "Anthropology": { ipa: "/ˌæn.θrəˈpɒl.ə.dʒi/", meaning: "Nhân chủng học", paraphrase: "She studied <strong>anthropology</strong> to understand different cultures around the world.", type: "noun", paragraph: "A" },
                    "Scholarly": { ipa: "/ˈskɒl.ə.li/", meaning: "Học thuật, uyên bác", paraphrase: "The professor published several <strong>scholarly</strong> articles in prestigious journals.", type: "adjective", paragraph: "A" },
                    "Whet sb appetite": { ipa: "/wet ˈæp.ɪ.taɪt/", meaning: "Kích thích sự thèm muốn", paraphrase: "The preview really <strong>whetted my appetite</strong> for the full documentary.", type: "phrase", paragraph: "A" },
                    "Doggedly": { ipa: "/ˈdɒɡ.ɪd.li/", meaning: "Bền bỉ, kiên trì", paraphrase: "Despite many rejections, she <strong>doggedly</strong> pursued her research goals.", type: "adverb", paragraph: "A" },
                    "Preface": { ipa: "/ˈpref.əs/", meaning: "Lời nói đầu, lời tựa", paraphrase: "The author's <strong>preface</strong> explained the inspiration behind the book.", type: "noun", paragraph: "A" },
                    "Accounts": { ipa: "/əˈkaʊnts/", meaning: "Tường thuật, câu chuyện", paraphrase: "Historians rely on first-hand <strong>accounts</strong> to understand past events.", type: "noun", paragraph: "A" },
                    "Purist": { ipa: "/ˈpjʊə.rɪst/", meaning: "Người theo chủ nghĩa thuần túy", paraphrase: "As a language <strong>purist</strong>, he refused to use modern slang in his writing.", type: "noun", paragraph: "B" },
                    "Elicit": { ipa: "/ɪˈlɪs.ɪt/", meaning: "Gợi ra, moi ra, khơi gợi", paraphrase: "The interviewer tried to <strong>elicit</strong> honest responses from the participants.", type: "verb", paragraph: "B" },
                    "Fieldwork": { ipa: "/ˈfiːld.wɜːk/", meaning: "Nghiên cứu thực địa", paraphrase: "The anthropologist spent two years doing <strong>fieldwork</strong> in remote villages.", type: "noun", paragraph: "C" },
                    "Reticent": { ipa: "/ˈret.ɪ.sənt/", meaning: "Kín đáo, dè dặt", paraphrase: "She was <strong>reticent</strong> about sharing details of her personal life.", type: "adjective", paragraph: "C" },
                    "Ethical": { ipa: "/ˈeθ.ɪ.kəl/", meaning: "Có đạo đức, thuộc về đạo đức", paraphrase: "Researchers must follow <strong>ethical</strong> guidelines when working with human subjects.", type: "adjective", paragraph: "C" },
                    "Attire": { ipa: "/əˈtaɪər/", meaning: "Mặc quần áo chỉnh tề", paraphrase: "Guests were asked to <strong>attire</strong> themselves in formal evening wear.", type: "verb", paragraph: "D" },
                    "Vouch for": { ipa: "/vaʊtʃ fɔːr/", meaning: "Bảo đảm cho, xác nhận", paraphrase: "I can <strong>vouch for</strong> her reliability as she has never let me down.", type: "phrasal verb", paragraph: "E" },
                    "Disclose": { ipa: "/dɪˈskləʊz/", meaning: "Tiết lộ, công khai", paraphrase: "The company refused to <strong>disclose</strong> details about the new product launch.", type: "verb", paragraph: "E" },
                    "Matter-of-fact manner": { ipa: "/ˌmæt.ər.əvˈfækt ˈmæn.ər/", meaning: "Thái độ thực tế, không cảm xúc", paraphrase: "She delivered the bad news in a <strong>matter-of-fact manner</strong> without emotion.", type: "phrase", paragraph: "G" },
                    "Clam up": { ipa: "/klæm ʌp/", meaning: "Im bặt, câm như hến", paraphrase: "Whenever the topic of money comes up, he <strong>clams up</strong> immediately.", type: "phrasal verb", paragraph: "G" },
                    "Curiosity": { ipa: "/ˌkjʊə.riˈɒs.ə.ti/", meaning: "Sự tò mò, tính hiếu kỳ", paraphrase: "Scientific <strong>curiosity</strong> drives researchers to explore the unknown.", type: "noun", paragraph: "G" },
                    "Contradict": { ipa: "/ˌkɒn.trəˈdɪkt/", meaning: "Mâu thuẫn, trái ngược", paraphrase: "The witness's statement <strong>contradicted</strong> earlier police reports.", type: "verb", paragraph: "H" },
                    "Misconception": { ipa: "/ˌmɪs.kənˈsep.ʃən/", meaning: "Sự hiểu lầm", paraphrase: "There's a common <strong>misconception</strong> that all snakes are poisonous.", type: "noun", paragraph: "H" },
                    "Outline": { ipa: "/ˈaʊt.laɪn/", meaning: "Dàn ý, phác thảo", paraphrase: "The teacher asked students to create an <strong>outline</strong> before writing their essays.", type: "noun", paragraph: "H" }
                },
                "A New Planet": {
                    "extra-terrestrial life": { ipa: "/ˌek.strə.təˈres.tri.əl laɪf/", meaning: "Sự sống ngoài Trái Đất", paraphrase: "Scientists continue searching for evidence of <strong>extra-terrestrial life</strong> in our solar system.", type: "noun phrase", paragraph: "A" },
                    "astronomers": { ipa: "/əˈstrɒn.ə.mərz/", meaning: "Các nhà thiên văn học", paraphrase: "<strong>Astronomers</strong> discovered a new galaxy using advanced telescopes.", type: "noun", paragraph: "A" },
                    "criterion": { ipa: "/kraɪˈtɪə.ri.ən/", meaning: "Tiêu chí", paraphrase: "The main <strong>criterion</strong> for selection is academic excellence.", type: "noun", paragraph: "A" },
                    "organism": { ipa: "/ˈɔː.ɡən.ɪ.zəm/", meaning: "Sinh vật", paraphrase: "This microscopic <strong>organism</strong> can survive in extreme conditions.", type: "noun", paragraph: "A" },
                    "harbour": { ipa: "/ˈhɑː.bər/", meaning: "Chứa đựng, che chở", paraphrase: "The cave may <strong>harbour</strong> unique species yet to be discovered.", type: "verb", paragraph: "A" },
                    "formation": { ipa: "/fɔːˈmeɪ.ʃən/", meaning: "Sự hình thành", paraphrase: "The <strong>formation</strong> of planets takes millions of years.", type: "noun", paragraph: "A" },
                    "habitable zone": { ipa: "/ˈhæb.ɪ.tə.bəl zəʊn/", meaning: "Vùng có thể sống được", paraphrase: "The planet orbits within the star's <strong>habitable zone</strong> where water could exist.", type: "noun phrase", paragraph: "B" },
                    "toehold": { ipa: "/ˈtəʊ.həʊld/", meaning: "Chỗ đứng, chỗ bám vững chắc", paraphrase: "The company gained a <strong>toehold</strong> in the Asian market last year.", type: "noun", paragraph: "B" },
                    "exude": { ipa: "/ɪɡˈzjuːd/", meaning: "Tiết ra, tỏa ra", paraphrase: "The plant <strong>exudes</strong> a sweet fragrance that attracts insects.", type: "verb", paragraph: "C" },
                    "boast": { ipa: "/bəʊst/", meaning: "Sở hữu, với sự tự hào", paraphrase: "The hotel <strong>boasts</strong> panoramic views of the ocean.", type: "verb", paragraph: "D" },
                    "precision": { ipa: "/prɪˈsɪʒ.ən/", meaning: "Độ chính xác", paraphrase: "The surgery requires extreme <strong>precision</strong> and careful attention.", type: "noun", paragraph: "D" },
                    "be amenable to": { ipa: "/bi əˈmiː.nə.bəl tuː/", meaning: "Dễ bị tác động", paraphrase: "The committee was <strong>amenable to</strong> suggestions from the public.", type: "phrase", paragraph: "E" },
                    "light spectrum": { ipa: "/laɪt ˈspek.trəm/", meaning: "Quang phổ ánh sáng", paraphrase: "Scientists analyze the <strong>light spectrum</strong> to determine a star's composition.", type: "noun phrase", paragraph: "E" },
                    "vessel": { ipa: "/ˈves.əl/", meaning: "Tàu, thuyền; mạch máu; vật chứa", paraphrase: "The research <strong>vessel</strong> departed for a three-month expedition.", type: "noun", paragraph: "E" },
                    "molecule": { ipa: "/ˈmɒl.ɪ.kjuːl/", meaning: "Phân tử", paraphrase: "Water is composed of <strong>molecules</strong> containing hydrogen and oxygen.", type: "noun", paragraph: "E" },
                    "glare": { ipa: "/ɡleər/", meaning: "Ánh sáng chói, chói lóa", paraphrase: "The <strong>glare</strong> from the sun made it difficult to see the road.", type: "noun", paragraph: "E" }
                },
                "Male Body": {
                    "Prevailing": { ipa: "/prɪˈveɪ.lɪŋ/", meaning: "Phổ biến, thịnh hành", paraphrase: "The <strong>prevailing</strong> opinion is that technology improves our lives.", type: "adjective", paragraph: "A" },
                    "Notion": { ipa: "/ˈnəʊ.ʃən/", meaning: "Quan niệm, ý kiến", paraphrase: "She had the <strong>notion</strong> that success would come easily.", type: "noun", paragraph: "A" },
                    "Static": { ipa: "/ˈstæt.ɪk/", meaning: "Tĩnh, không thay đổi", paraphrase: "The economy remained <strong>static</strong> despite government intervention.", type: "adjective", paragraph: "A" },
                    "Silhouette": { ipa: "/ˌsɪl.uˈet/", meaning: "Hình bóng, bóng dáng", paraphrase: "We could see the <strong>silhouette</strong> of the mountains against the sunset.", type: "noun", paragraph: "B" },
                    "Slender": { ipa: "/ˈslen.dər/", meaning: "Mảnh khảnh, thon thả", paraphrase: "The dancer had a <strong>slender</strong> and graceful figure.", type: "adjective", paragraph: "B" },
                    "Edgy": { ipa: "/ˈedʒ.i/", meaning: "Gai góc, khác biệt", paraphrase: "The designer's <strong>edgy</strong> clothing style appeals to young urbanites.", type: "adjective", paragraph: "B" },
                    "Androgynous": { ipa: "/ænˈdrɒdʒ.ɪ.nəs/", meaning: "Phi giới tính", paraphrase: "The model's <strong>androgynous</strong> look challenges traditional gender norms.", type: "adjective", paragraph: "B" },
                    "Towering": { ipa: "/ˈtaʊə.rɪŋ/", meaning: "Cao lớn", paraphrase: "The <strong>towering</strong> skyscrapers dominated the city skyline.", type: "adjective", paragraph: "B" },
                    "Squeeze out": { ipa: "/skwiːz aʊt/", meaning: "Ép ra, vắt kiệt", paraphrase: "Large corporations often <strong>squeeze out</strong> smaller competitors from the market.", type: "phrasal verb", paragraph: "C" },
                    "Trouser": { ipa: "/ˈtraʊ.zər/", meaning: "Quần tây", paraphrase: "He bought a new pair of <strong>trousers</strong> for the job interview.", type: "noun", paragraph: "C" },
                    "Waistline": { ipa: "/ˈweɪst.laɪn/", meaning: "Vòng eo", paraphrase: "Regular exercise can help reduce your <strong>waistline</strong> significantly.", type: "noun", paragraph: "C" },
                    "Physique": { ipa: "/fɪˈziːk/", meaning: "Thể chất, vóc dáng", paraphrase: "Athletes train for years to develop their impressive <strong>physique</strong>.", type: "noun", paragraph: "C" },
                    "Go to great lengths to": { ipa: "/ɡəʊ tə ɡreɪt leŋθs tuː/", meaning: "Dùng nhiều công sức", paraphrase: "Parents will <strong>go to great lengths to</strong> ensure their children's safety.", type: "phrase", paragraph: "D" },
                    "Surgical": { ipa: "/ˈsɜː.dʒɪ.kəl/", meaning: "Thuộc về phẫu thuật", paraphrase: "The patient required <strong>surgical</strong> intervention to repair the damaged tissue.", type: "adjective", paragraph: "D" },
                    "Liposuction": { ipa: "/ˈlɪp.əʊˌsʌk.ʃən/", meaning: "Hút mỡ", paraphrase: "He considered <strong>liposuction</strong> as a quick solution for weight loss.", type: "noun", paragraph: "D" },
                    "Eating disorder": { ipa: "/ˈiː.tɪŋ dɪˌsɔː.dər/", meaning: "Rối loạn ăn uống", paraphrase: "Anorexia is a serious <strong>eating disorder</strong> that requires professional treatment.", type: "noun phrase", paragraph: "E" },
                    "Binge": { ipa: "/bɪndʒ/", meaning: "Làm điều gì đó quá mức, không kiểm soát", paraphrase: "After the diet ended, she would <strong>binge</strong> on junk food every weekend.", type: "verb", paragraph: "E" },
                    "Induce": { ipa: "/ɪnˈdjuːs/", meaning: "Gây ra, xui khiến", paraphrase: "Stress can <strong>induce</strong> physical symptoms like headaches and fatigue.", type: "verb", paragraph: "E" },
                    "Vomit": { ipa: "/ˈvɒm.ɪt/", meaning: "Nôn mửa", paraphrase: "The food poisoning caused him to <strong>vomit</strong> throughout the night.", type: "verb", paragraph: "E" },
                    "Afflict": { ipa: "/əˈflɪkt/", meaning: "Ảnh hưởng tiêu cực", paraphrase: "Poverty continues to <strong>afflict</strong> millions of people worldwide.", type: "verb", paragraph: "E" },
                    "Thrust": { ipa: "/θrʌst/", meaning: "Đẩy, nhét mạnh", paraphrase: "She <strong>thrust</strong> the letter into his hands and walked away.", type: "verb", paragraph: "E" },
                    "Bulimia": { ipa: "/buːˈlɪm.i.ə/", meaning: "Chứng cuồng ăn, sau đó nôn ra để không bị tăng cân", paraphrase: "People with <strong>bulimia</strong> often struggle with cycles of bingeing and purging.", type: "noun", paragraph: "E" },
                    "Complement": { ipa: "/ˈkɒm.plɪ.ment/", meaning: "Bổ sung, làm đầy đủ", paraphrase: "The red wine perfectly <strong>complements</strong> the grilled steak.", type: "verb", paragraph: "F" },
                    "Displace": { ipa: "/dɪˈspleɪs/", meaning: "Thay thế, di dời", paraphrase: "Digital cameras have <strong>displaced</strong> traditional film cameras in most markets.", type: "verb", paragraph: "F" },
                    "Recession": { ipa: "/rɪˈseʃ.ən/", meaning: "Suy thoái kinh tế", paraphrase: "The country entered a severe <strong>recession</strong> following the financial crisis.", type: "noun", paragraph: "F" },
                    "Masculine": { ipa: "/ˈmæs.kjə.lɪn/", meaning: "Nam tính", paraphrase: "Society often associates certain traits with <strong>masculine</strong> behavior.", type: "adjective", paragraph: "F" },
                    "Fall out of favor": { ipa: "/fɔːl aʊt əv ˈfeɪ.vər/", meaning: "Không còn được ưa chuộng", paraphrase: "Traditional teaching methods have <strong>fallen out of favor</strong> with modern educators.", type: "phrase", paragraph: "F" },
                    "Weather": { ipa: "/ˈweð.ər/", meaning: "Vượt qua, chịu đựng", paraphrase: "The company managed to <strong>weather</strong> the economic storm successfully.", type: "verb", paragraph: "F" },
                    "Flounder": { ipa: "/ˈflaʊn.dər/", meaning: "Vật lộn, lúng túng", paraphrase: "Without clear direction, the project began to <strong>flounder</strong> after six months.", type: "verb", paragraph: "F" },
                    "Correlation": { ipa: "/ˌkɒr.əˈleɪ.ʃən/", meaning: "Sự tương quan", paraphrase: "Researchers found a strong <strong>correlation</strong> between exercise and mental health.", type: "noun", paragraph: "F" },
                    "Effeminacy": { ipa: "/ɪˈfem.ɪ.nə.si/", meaning: "Sự ẻo lả, nữ tính", paraphrase: "Historical attitudes toward <strong>effeminacy</strong> in men have evolved significantly.", type: "noun", paragraph: "F" },
                    "Pronounced": { ipa: "/prəˈnaʊnst/", meaning: "Rõ rệt, dễ thấy", paraphrase: "There was a <strong>pronounced</strong> difference in quality between the two products.", type: "adjective", paragraph: "F" },
                    "Polarized ideas": { ipa: "/ˈpəʊ.lə.raɪzd aɪˈdɪəz/", meaning: "Những ý kiến phân cực", paraphrase: "The debate featured <strong>polarized ideas</strong> about climate change policy.", type: "noun phrase", paragraph: "G" },
                    "Columnist": { ipa: "/ˈkɒl.əm.nɪst/", meaning: "Người viết chuyên mục", paraphrase: "The newspaper <strong>columnist</strong> writes about political issues every Sunday.", type: "noun", paragraph: "G" },
                    "Exude": { ipa: "/ɪɡˈzjuːd/", meaning: "Tiết ra, tỏa ra", paraphrase: "The successful CEO <strong>exudes</strong> confidence in every business meeting.", type: "verb", paragraph: "G" },
                    "Destabilize": { ipa: "/diːˈsteɪ.bɪ.laɪz/", meaning: "Gây bất ổn", paraphrase: "The scandal threatened to <strong>destabilize</strong> the entire government.", type: "verb", paragraph: "G" },
                    "Futile": { ipa: "/ˈfjuː.taɪl/", meaning: "Vô nghĩa", paraphrase: "All attempts to rescue the trapped miners proved <strong>futile</strong> in the end.", type: "adjective", paragraph: "H" }
                }
            }
        }
    },
    listening: {
        1: { inclass: {}, homework: {} },
        2: { inclass: {}, homework: {} },
        3: { inclass: {}, homework: {} },
        4: { inclass: {}, homework: {} },
        5: { inclass: {}, homework: {} },
        6: { 
            inclass: {},
            homework: {
                "Straightforward": { ipa: "/ˌstreɪtˈfɔː.wəd/", meaning: "Thẳng thắn, dễ hiểu", paraphrase: "The instructions were <strong>straightforward</strong> and easy to follow.", type: "adjective" },
                "Collate": { ipa: "/kəˈleɪt/", meaning: "Thu thập và sắp xếp", paraphrase: "Please <strong>collate</strong> all the survey responses into a single report.", type: "verb" },
                "Exhibit": { ipa: "/ɪɡˈzɪb.ɪt/", meaning: "Trưng bày", paraphrase: "The museum will <strong>exhibit</strong> the artist's paintings next month.", type: "verb" },
                "Get sth out of the way": { ipa: "/ɡet aʊt əv ðə weɪ/", meaning: "Xử lý xong cái gì đó", paraphrase: "Let's <strong>get this paperwork out of the way</strong> before starting the project.", type: "phrase" },
                "Order of importance": { ipa: "/ˈɔː.dər əv ɪmˈpɔː.təns/", meaning: "Thứ tự ưu tiên", paraphrase: "List your tasks in <strong>order of importance</strong> to manage your time effectively.", type: "phrase" },
                "First-hand experience": { ipa: "/ˌfɜːst ˈhænd ɪkˈspɪə.ri.əns/", meaning: "Kinh nghiệm thực tế", paraphrase: "She gained <strong>first-hand experience</strong> of farm life during her summer internship.", type: "phrase" },
                "Background reading": { ipa: "/ˈbæk.ɡraʊnd ˈriː.dɪŋ/", meaning: "Đọc kiến thức nền", paraphrase: "Do some <strong>background reading</strong> on the topic before the lecture.", type: "phrase" },
                "Settle in": { ipa: "/ˈset.əl ɪn/", meaning: "Làm quen, ổn định", paraphrase: "It took me a few weeks to <strong>settle in</strong> at my new job.", type: "phrasal verb" },
                "Make sense": { ipa: "/meɪk sens/", meaning: "Có lý, hợp lý", paraphrase: "Her explanation didn't <strong>make sense</strong> given the evidence presented.", type: "phrase" },
                "Legible": { ipa: "/ˈledʒ.ə.bəl/", meaning: "Chữ rõ ràng, dễ đọc", paraphrase: "Make sure your handwriting is <strong>legible</strong> for the exam.", type: "adjective" },
                "Jot down": { ipa: "/dʒɒt daʊn/", meaning: "Ghi chép nhanh", paraphrase: "<strong>Jot down</strong> any ideas that come to you during the meeting.", type: "phrasal verb" },
                "Laboratory": { ipa: "/ləˈbɒr.ə.tər.i/", meaning: "Phòng thí nghiệm", paraphrase: "The scientists conducted their experiments in the <strong>laboratory</strong>.", type: "noun" },
                "Theory": { ipa: "/ˈθɪə.ri/", meaning: "Lý thuyết, học thuyết", paraphrase: "Einstein's <strong>theory</strong> of relativity revolutionized physics.", type: "noun" },
                "Abide by": { ipa: "/əˈbaɪd baɪ/", meaning: "Tuân theo, chấp hành", paraphrase: "All employees must <strong>abide by</strong> the company's safety regulations.", type: "phrasal verb" },
                "Procedures": { ipa: "/prəˈsiː.dʒərz/", meaning: "Quy trình, thủ tục", paraphrase: "Follow the proper <strong>procedures</strong> when handling hazardous materials.", type: "noun" },
                "Safety glasses": { ipa: "/ˈseɪf.ti ɡlæs.ɪz/", meaning: "Kính bảo hộ", paraphrase: "Wear <strong>safety glasses</strong> at all times in the workshop.", type: "noun" },
                "Goggles": { ipa: "/ˈɡɒɡ.əlz/", meaning: "Kính bảo hộ (ôm sát mặt)", paraphrase: "Swimmers often wear <strong>goggles</strong> to protect their eyes from chlorine.", type: "noun" },
                "Hazard": { ipa: "/ˈhæz.əd/", meaning: "Mối nguy hiểm", paraphrase: "Slippery floors are a serious <strong>hazard</strong> in this workplace.", type: "noun" },
                "Trainers": { ipa: "/ˈtreɪ.nərz/", meaning: "Giày thể thao", paraphrase: "You'll need comfortable <strong>trainers</strong> for the hiking trip.", type: "noun" },
                "Thorough": { ipa: "/ˈθʌr.ə/", meaning: "Kỹ lưỡng, tỉ mỉ", paraphrase: "The detective conducted a <strong>thorough</strong> investigation of the crime scene.", type: "adjective" }
            }
        },
        7: {
            inclass: {
                "Mass Strandings of Whales and Dolphins": {
                    "field work": { ipa: "/ˈfiːld wɜːk/", meaning: "Nghiên cứu thực địa", paraphrase: "Marine biologists conduct <strong>field work</strong> to study whales in their natural habitat.", type: "noun phrase" },
                    "ashore": { ipa: "/əˈʃɔːr/", meaning: "Vào bờ", paraphrase: "Several dolphins were found washed <strong>ashore</strong> after the storm.", type: "adverb" },
                    "mass strandings": { ipa: "/mæs ˈstrændɪŋz/", meaning: "Sự mắc cạn hàng loạt", paraphrase: "Scientists are investigating the cause of recent <strong>mass strandings</strong> along the coast.", type: "noun phrase" },
                    "occurrence": { ipa: "/əˈkʌr.əns/", meaning: "Sự xuất hiện, sự xảy ra", paraphrase: "These whale strandings are a regular <strong>occurrence</strong> in this region during winter.", type: "noun" },
                    "parasites": { ipa: "/ˈpær.ə.saɪts/", meaning: "Ký sinh trùng", paraphrase: "The examination revealed high levels of <strong>parasites</strong> in the whale's digestive system.", type: "noun" },
                    "infested": { ipa: "/ɪnˈfes.tɪd/", meaning: "Bị nhiễm, bị xâm chiếm", paraphrase: "The old wooden ship was completely <strong>infested</strong> with termites.", type: "adjective" },
                    "navigate": { ipa: "/ˈnæv.ɪ.ɡeɪt/", meaning: "Định hướng, điều hướng", paraphrase: "Whales use echolocation to <strong>navigate</strong> through dark ocean waters.", type: "verb" },
                    "feed": { ipa: "/fiːd/", meaning: "Kiếm ăn", paraphrase: "The whales travel to these waters to <strong>feed</strong> on abundant krill populations.", type: "verb" },
                    "fatal": { ipa: "/ˈfeɪ.təl/", meaning: "Chết người, gây tử vong", paraphrase: "The accident proved <strong>fatal</strong> for three of the passengers.", type: "adjective" },
                    "chase": { ipa: "/tʃeɪs/", meaning: "Rượt đuổi, săn đuổi", paraphrase: "The orcas <strong>chase</strong> their prey into shallow waters where they become trapped.", type: "verb" },
                    "beach": { ipa: "/biːtʃ/", meaning: "Dạt vào bờ, mắc cạn", paraphrase: "In panic, the dolphins may <strong>beach</strong> themselves while fleeing predators.", type: "verb" },
                    "squid": { ipa: "/skwɪd/", meaning: "Mực", paraphrase: "Sperm whales primarily <strong>feed</strong> on giant <strong>squid</strong> in deep ocean trenches.", type: "noun" },
                    "stomach contents": { ipa: "/ˈstʌm.ək ˈkɒn.tents/", meaning: "Thành phần trong dạ dày", paraphrase: "Analysis of the whale's <strong>stomach contents</strong> revealed plastic pollution.", type: "noun phrase" },
                    "pinpoint": { ipa: "/ˈpɪn.pɔɪnt/", meaning: "Xác định chính xác", paraphrase: "Researchers are trying to <strong>pinpoint</strong> the exact location of the breeding grounds.", type: "verb" },
                    "coincide": { ipa: "/ˌkəʊ.ɪnˈsaɪd/", meaning: "Trùng khớp, xảy ra cùng lúc", paraphrase: "The whale migration seems to <strong>coincide</strong> with seasonal plankton blooms.", type: "verb" },
                    "submarine": { ipa: "/ˌsʌb.məˈriːn/", meaning: "Tàu ngầm", paraphrase: "Military <strong>submarine</strong> exercises may disrupt marine mammal communication.", type: "noun" },
                    "detection": { ipa: "/dɪˈtek.ʃən/", meaning: "Sự phát hiện", paraphrase: "Early <strong>detection</strong> of health issues improves survival rates for stranded animals.", type: "noun" },
                    "spread out": { ipa: "/spred aʊt/", meaning: "Trải rộng ra, phân tán", paraphrase: "The rescue team had to <strong>spread out</strong> along five kilometers of coastline.", type: "phrasal verb" },
                    "inevitable": { ipa: "/ɪˈnev.ɪ.tə.bəl/", meaning: "Không thể tránh khỏi", paraphrase: "Given the severity of injuries, euthanasia was <strong>inevitable</strong> for some whales.", type: "adjective" }
                }
            },
            homework: {}
        },
        8: { inclass: {}, homework: {} }
    }
};
