// ==========================================
// IELTS VOCAB DATA
// ==========================================
// Cập nhật từ vựng ở file này, không cần động vào index.html

const VOCAB_DATA = {
    reading: {
        1: {
            inclass: {
                "Acknowledge": { ipa: "/əkˈnɒl.ɪdʒ/", meaning: "Thừa nhận, công nhận", paraphrase: "Accept or admit the existence or truth of something", type: "verb" },
                "Aggregate": { ipa: "/ˈæɡ.rɪ.ɡət/", meaning: "Tổng hợp, kết hợp", paraphrase: "A whole formed by combining several elements", type: "noun/verb" },
                "Allocate": { ipa: "/ˈæl.ə.keɪt/", meaning: "Phân bổ", paraphrase: "Distribute resources or duties for a particular purpose", type: "verb" },
                "Ambiguous": { ipa: "/æmˈbɪɡ.ju.əs/", meaning: "Mơ hồ, lưỡng nghĩa", paraphrase: "Open to more than one interpretation", type: "adjective" },
                "Amend": { ipa: "/əˈmend/", meaning: "Sửa đổi, cải thiện", paraphrase: "Make minor changes to make it fairer or more accurate", type: "verb" },
                "Analogy": { ipa: "/əˈnæl.ə.dʒi/", meaning: "Sự tương tự", paraphrase: "A comparison between two things for explanation", type: "noun" },
                "Arbitrary": { ipa: "/ˈɑː.bɪ.trər.i/", meaning: "Tùy tiện, độc đoán", paraphrase: "Based on random choice rather than reason", type: "adjective" },
                "Assemble": { ipa: "/əˈsem.bəl/", meaning: "Tập hợp, lắp ráp", paraphrase: "Gather together in one place for a common purpose", type: "verb" },
                "Attain": { ipa: "/əˈteɪn/", meaning: "Đạt được", paraphrase: "Succeed in achieving something that one desires", type: "verb" },
                "Attribute": { ipa: "/əˈtrɪb.juːt/", meaning: "Thuộc tính, quy cho", paraphrase: "Regard something as being caused by", type: "noun/verb" },
                "Bias": { ipa: "/ˈbaɪ.əs/", meaning: "Thành kiến, thiên vị", paraphrase: "Prejudice in favor of or against one thing", type: "noun" },
                "Bulk": { ipa: "/bʌlk/", meaning: "Phần lớn, số lượng lớn", paraphrase: "The mass or magnitude of something large", type: "noun" },
                "Coherent": { ipa: "/kəʊˈhɪə.rənt/", meaning: "Mạch lạc, chặt chẽ", paraphrase: "Logical and consistent", type: "adjective" },
                "Coincide": { ipa: "/ˌkəʊ.ɪnˈsaɪd/", meaning: "Trùng hợp", paraphrase: "Occur at or during the same time", type: "verb" },
                "Commodity": { ipa: "/kəˈmɒd.ə.ti/", meaning: "Hàng hóa", paraphrase: "A raw material or primary agricultural product", type: "noun" },
                "Compatible": { ipa: "/kəmˈpæt.ə.bəl/", meaning: "Tương thích", paraphrase: "Able to exist or occur together without conflict", type: "adjective" },
                "Compile": { ipa: "/kəmˈpaɪl/", meaning: "Biên soạn, thu thập", paraphrase: "Produce by assembling information from other sources", type: "verb" },
                "Complement": { ipa: "/ˈkɒm.plɪ.ment/", meaning: "Bổ sung", paraphrase: "A thing that completes or brings to perfection", type: "noun/verb" },
                "Conceive": { ipa: "/kənˈsiːv/", meaning: "Hình thành trong đầu", paraphrase: "Form or devise a plan or idea in the mind", type: "verb" },
                "Concurrent": { ipa: "/kənˈkʌr.ənt/", meaning: "Đồng thời", paraphrase: "Existing, happening, or done at the same time", type: "adjective" }
            },
            homework: {}
        },
        2: { 
            inclass: {}, 
            homework: {"petition": { ipa: "/pəˈtɪʃ.ən/", meaning: "đơn kiến nghị", paraphrase: "A formal written request", type: "noun" },
      "discontent": { ipa: "/ˌdɪs.kənˈtent/", meaning: "sự bất mãn", paraphrase: "A feeling of dissatisfaction", type: "noun" },
      "social unrest": { ipa: "/ˌsəʊ.ʃəl ʌnˈrest/", meaning: "bất ổn xã hội", paraphrase: "Widespread public dissatisfaction", type: "noun phrase" },
      "appalling": { ipa: "/əˈpɔː.lɪŋ/", meaning: "kinh khủng", paraphrase: "Causing shock or dismay", type: "adjective" },
      "suffrage": { ipa: "/ˈsʌf.rɪdʒ/", meaning: "quyền bầu cử", paraphrase: "The right to vote", type: "noun" },
      "trade union": { ipa: "/ˌtreɪd ˈjuː.njən/", meaning: "công đoàn", paraphrase: "Association of workers", type: "noun phrase" },
      "collapse": { ipa: "/kəˈlæps/", meaning: "sụp đổ", paraphrase: "To fall down suddenly", type: "verb" },
      "subsequent": { ipa: "/ˈsʌb.sɪ.kwənt/", meaning: "tiếp theo", paraphrase: "Coming after something", type: "adjective" },
      "disillusionment": { ipa: "/ˌdɪs.ɪˈluː.ʒən.mənt/", meaning: "vỡ mộng", paraphrase: "Feeling of disappointment", type: "noun" },
      "found": { ipa: "/faʊnd/", meaning: "thành lập", paraphrase: "To establish", type: "verb" },
      "reform parliament": { ipa: "/rɪˈfɔːm ˈpɑː.lɪə.mənt/", meaning: "quốc hội cải cách", paraphrase: "Legislative body focused on reform", type: "noun phrase" },
      "champion": { ipa: "/ˈtʃæm.pi.ən/", meaning: "ủng hộ, bảo vệ", paraphrase: "To support or fight for", type: "verb" },
      "key figure": { ipa: "/kiː ˈfɪɡ.ər/", meaning: "nhân vật chủ chốt", paraphrase: "Important person", type: "noun phrase" },
      "delegate": { ipa: "/ˈdel.ɪ.ɡət/", meaning: "đại biểu", paraphrase: "Authorized representative", type: "noun" },
      "proclaim": { ipa: "/prəˈkleɪm/", meaning: "tuyên bố", paraphrase: "To announce officially", type: "verb" },
      "sacred": { ipa: "/ˈseɪ.krɪd/", meaning: "thiêng liêng", paraphrase: "Connected with God", type: "adjective" },
      "dismiss": { ipa: "/dɪsˈmɪs/", meaning: "bác bỏ", paraphrase: "To reject or send away", type: "verb" },
      "troops": { ipa: "/truːps/", meaning: "quân đội", paraphrase: "Soldiers", type: "noun" },
      "miner": { ipa: "/ˈmaɪ.nər/", meaning: "thợ mỏ", paraphrase: "Person working in a mine", type: "noun" },
      "crush": { ipa: "/krʌʃ/", meaning: "đàn áp", paraphrase: "To defeat completely", type: "verb" },
      "riot": { ipa: "/ˈraɪ.ət/", meaning: "bạo loạn", paraphrase: "Violent disturbance", type: "noun" },
      "abandon": { ipa: "/əˈbæn.dən/", meaning: "từ bỏ", paraphrase: "To give up completely", type: "verb" },
      "the cause": { ipa: "/ðə kɔːz/", meaning: "sự nghiệp", paraphrase: "A principle to fight for", type: "noun phrase" },
      "prominence": { ipa: "/ˈprɒm.ɪ.nəns/", meaning: "nổi bật", paraphrase: "State of being important", type: "noun" },
      "procession": { ipa: "/prəˈseʃ.ən/", meaning: "diễu hành", paraphrase: "Orderly movement of people", type: "noun" },
      "take precaution": { ipa: "/teɪk prɪˈkɔː.ʃən/", meaning: "đề phòng", paraphrase: "To act to prevent danger", type: "verb phrase" },
      "discredit": { ipa: "/dɪˈskred.ɪt/", meaning: "làm mất uy tín", paraphrase: "To harm reputation", type: "verb" },
      "fiasco": { ipa: "/fiˈæs.kəʊ/", meaning: "thất bại thảm hại", paraphrase: "Complete failure", type: "noun" },
      "abolition": { ipa: "/ˌæb.əˈlɪʃ.ən/", meaning: "bãi bỏ", paraphrase: "Act of ending something", type: "noun" },
      "far ahead of the times": { ipa: "/fɑːr əˈhed əv ðə taɪmz/", meaning: "vượt thời đại", paraphrase: "Too advanced for current era", type: "phrase" },
      "resolute action": { ipa: "/ˈrez.ə.luːt ˈæk.ʃən/", meaning: "hành động kiên quyết", paraphrase: "Firm measures", type: "noun phrase" },
      "suppress": { ipa: "/səˈpres/", meaning: "đàn áp", paraphrase: "To forcibly put an end to", type: "verb" },
      "rejection": { ipa: "/rɪˈdʒek.ʃən/", meaning: "từ chối", paraphrase: "Act of refusing", type: "noun" },
      "radical": { ipa: "/ˈræd.ɪ.kəl/", meaning: "cấp tiến", paraphrase: "Fundamental change", type: "adjective" },
      "austerity measures": { ipa: "/ɒˈster.ə.ti ˈmeʒ.əz/", meaning: "thắt lưng buộc bụng", paraphrase: "Spending cuts", type: "noun phrase" },
      "slash": { ipa: "/slæʃ/", meaning: "cắt giảm", paraphrase: "To reduce drastically", type: "verb" },
      "hike tax": { ipa: "/haɪk tæks/", meaning: "tăng thuế", paraphrase: "To increase taxes", type: "verb phrase" },
      "impose": { ipa: "/ɪmˈpəʊz/", meaning: "áp đặt", paraphrase: "To force acceptance", type: "verb" },
      "deficit": { ipa: "/ˈdef.ɪ.sɪt/", meaning: "thâm hụt", paraphrase: "Shortfall", type: "noun" },
      "unsustainable": { ipa: "/ˌʌn.səsˈteɪ.nə.bəl/", meaning: "không bền vững", paraphrase: "Cannot be maintained", type: "adjective" },
      "roll over current loans": { ipa: "/rəʊl ˈəʊ.və ˈkʌr.ənt ləʊnz/", meaning: "gia hạn vay", paraphrase: "Extend loan terms", type: "verb phrase" },
      "interest rate": { ipa: "/ˈɪn.trəst reɪt/", meaning: "lãi suất", paraphrase: "Loan interest percentage", type: "noun phrase" },
      "curtail": { ipa: "/kɜːˈteɪl/", meaning: "cắt giảm", paraphrase: "To reduce", type: "verb" },
      "elevate": { ipa: "/ˈel.ɪ.veɪt/", meaning: "nâng cao", paraphrase: "To raise up", type: "verb" },
      "excise": { ipa: "/ˈek.saɪz/", meaning: "thuế tiêu thụ", paraphrase: "Tax on goods", type: "noun" },
      "narrow": { ipa: "/ˈnær.əʊ/", meaning: "thu hẹp", paraphrase: "To make less wide", type: "verb" },
      "allowance": { ipa: "/əˈlaʊ.əns/", meaning: "phụ cấp", paraphrase: "Amount given", type: "noun" },
      "succession": { ipa: "/səkˈseʃ.ən/", meaning: "kế tiếp", paraphrase: "Sequence", type: "noun" },
      "indict": { ipa: "/ɪnˈdaɪt/", meaning: "truy tố", paraphrase: "To formally accuse", type: "verb" },
      "crisis": { ipa: "/ˈkraɪ.sɪs/", meaning: "khủng hoảng", paraphrase: "Time of danger", type: "noun" },
      "soar": { ipa: "/sɔːr/", meaning: "tăng vọt", paraphrase: "To increase rapidly", type: "verb" },
      "turn sour": { ipa: "/tɜːn ˈsaʊər/", meaning: "trở nên xấu", paraphrase: "To become bad", type: "verb phrase" },
      "retract": { ipa: "/rɪˈtrækt/", meaning: "rút lại", paraphrase: "To withdraw", type: "verb" },
      "decimate": { ipa: "/ˈdes.ɪ.meɪt/", meaning: "tàn phá", paraphrase: "To destroy large part", type: "verb" },
      "out of work": { ipa: "/aʊt əv wɜːk/", meaning: "thất nghiệp", paraphrase: "Unemployed", type: "adjective phrase" },
      "implement": { ipa: "/ˈɪm.plɪ.ment/", meaning: "thực thi", paraphrase: "To put into effect", type: "verb" },
      "slump": { ipa: "/slʌmp/", meaning: "sụt giảm", paraphrase: "Severe fall", type: "noun" },
      "denounce": { ipa: "/dɪˈnaʊns/", meaning: "lên án", paraphrase: "To condemn publicly", type: "verb" },
      "frivolity": { ipa: "/frɪˈvɒl.ə.ti/", meaning: "phù phiếm", paraphrase: "Lack of seriousness", type: "noun" },
      "ratchet up": { ipa: "/ˈrætʃ.ɪt ʌp/", meaning: "tăng dần", paraphrase: "To increase gradually", type: "verb phrase" },
      "contract": { ipa: "/kənˈtrækt/", meaning: "co lại", paraphrase: "To decrease in size", type: "verb" }} },
        3: { inclass: {}, homework: {} },
        4: { inclass: {}, homework: {} },
        5: { inclass: {}, homework: {} },
        6: { inclass: {}, homework: {} },
        7: { inclass: {}, homework: {} }
    },
    listening: {
        1: { inclass: {}, homework: {} },
        2: { inclass: {}, homework: {} },
        3: { inclass: {}, homework: {} },
        4: { inclass: {}, homework: {} },
        5: { inclass: {}, homework: {} },
        6: { 
            inclass: {},
            homework: {
                "Straightforward": { ipa: "/ˌstreɪtˈfɔː.wəd/", meaning: "Thẳng thắn, dễ hiểu", paraphrase: "Easy to understand or simple", type: "adjective" },
                "Collate": { ipa: "/kəˈleɪt/", meaning: "Thu thập và sắp xếp", paraphrase: "Collect and arrange in proper order", type: "verb" },
                "Exhibit": { ipa: "/ɪɡˈzɪb.ɪt/", meaning: "Trưng bày", paraphrase: "Display or show publicly", type: "verb" },
                "Get sth out of the way": { ipa: "/ɡet aʊt əv ðə weɪ/", meaning: "Xử lý xong cái gì đó", paraphrase: "Complete or deal with something so it's no longer a concern", type: "phrase" },
                "Order of importance": { ipa: "/ˈɔː.dər əv ɪmˈpɔː.təns/", meaning: "Thứ tự ưu tiên", paraphrase: "Sequence based on how important things are", type: "phrase" },
                "First-hand experience": { ipa: "/ˌfɜːst ˈhænd ɪkˈspɪə.ri.əns/", meaning: "Kinh nghiệm thực tế", paraphrase: "Direct personal experience, not from others", type: "phrase" },
                "Background reading": { ipa: "/ˈbæk.ɡraʊnd ˈriː.dɪŋ/", meaning: "Đọc kiến thức nền", paraphrase: "Reading to gain foundational knowledge on a topic", type: "phrase" },
                "Settle in": { ipa: "/ˈset.əl ɪn/", meaning: "Làm quen, ổn định", paraphrase: "Become comfortable in a new situation", type: "phrasal verb" },
                "Make sense": { ipa: "/meɪk sens/", meaning: "Có lí, hợp lý", paraphrase: "Be logical or understandable", type: "phrase" },
                "Legible": { ipa: "/ˈledʒ.ə.bəl/", meaning: "Chữ rõ ràng, dễ đọc", paraphrase: "Clear enough to read", type: "adjective" },
                "Jot down": { ipa: "/dʒɒt daʊn/", meaning: "Ghi chép nhanh", paraphrase: "Write something quickly", type: "phrasal verb" },
                "Laboratory": { ipa: "/ləˈbɒr.ə.tər.i/", meaning: "Phòng thí nghiệm", paraphrase: "Room for scientific experiments and research", type: "noun" },
                "Theory": { ipa: "/ˈθɪə.ri/", meaning: "Lý thuyết, học thuyết", paraphrase: "Set of principles explaining something", type: "noun" },
                "Abide by": { ipa: "/əˈbaɪd baɪ/", meaning: "Tuân theo, chấp hành", paraphrase: "Follow or obey rules", type: "phrasal verb" },
                "Procedures": { ipa: "/prəˈsiː.dʒərz/", meaning: "Quy trình, thủ tục", paraphrase: "Established way of doing something", type: "noun" },
                "Safety glasses": { ipa: "/ˈseɪf.ti ɡlæs.ɪz/", meaning: "Kính bảo hộ", paraphrase: "Protective eyewear for safety", type: "noun" },
                "Goggles": { ipa: "/ˈɡɒɡ.əlz/", meaning: "Kính bảo hộ (ôm sát mặt)", paraphrase: "Close-fitting protective glasses", type: "noun" },
                "Hazard": { ipa: "/ˈhæz.əd/", meaning: "Mối nguy hiểm", paraphrase: "Source of danger", type: "noun" },
                "Trainers": { ipa: "/ˈtreɪ.nərz/", meaning: "Giày thể thao", paraphrase: "Athletic or sports shoes", type: "noun" },
                "Thorough": { ipa: "/ˈθʌr.ə/", meaning: "Kỹ lưỡng, tỉ mỉ", paraphrase: "Complete and careful", type: "adjective" }
            }
        },
        7: { inclass: {}, homework: {} },
        8: { inclass: {}, homework: {} }
    }
};
