// ==========================================
// IELTS VOCAB DATA - UPDATED WITH NESTED PASSAGES
// ==========================================
// Cập nhật từ vựng ở file này, không cần động vào index.html

const VOCAB_DATA = {
    reading: {
        1: {
            inclass: {
                "Acknowledge": { ipa: "/əkˈnɒl.ɪdʒ/", meaning: "Thừa nhận, công nhận", paraphrase: "Accept or admit the existence or truth of something", type: "verb" },
                "Aggregate": { ipa: "/ˈæɡ.rɪ.ɡət/", meaning: "Tổng hợp, kết hợp", paraphrase: "A whole formed by combining several elements", type: "noun/verb" },
                "Allocate": { ipa: "/ˈæl.ə.keɪt/", meaning: "Phân bổ", paraphrase: "Distribute resources or duties for a particular purpose", type: "verb" },
                "Ambiguous": { ipa: "/æmˈbɪɡ.ju.əs/", meaning: "Mơ hồ, lưỡng nghĩa", paraphrase: "Open to more than one interpretation", type: "adjective" },
                "Amend": { ipa: "/əˈmend/", meaning: "Sửa đổi, cải thiện", paraphrase: "Make minor changes to make it fairer or more accurate", type: "verb" },
                "Analogy": { ipa: "/əˈnæl.ə.dʒi/", meaning: "Sự tương tự", paraphrase: "A comparison between two things for explanation", type: "noun" },
                "Arbitrary": { ipa: "/ˈɑː.bɪ.trər.i/", meaning: "Tùy tiện, độc đoán", paraphrase: "Based on random choice rather than reason", type: "adjective" },
                "Assemble": { ipa: "/əˈsem.bəl/", meaning: "Tập hợp, lắp ráp", paraphrase: "Gather together in one place for a common purpose", type: "verb" },
                "Attain": { ipa: "/əˈteɪn/", meaning: "Đạt được", paraphrase: "Succeed in achieving something that one desires", type: "verb" },
                "Attribute": { ipa: "/əˈtrɪb.juːt/", meaning: "Thuộc tính, quy cho", paraphrase: "Regard something as being caused by", type: "noun/verb" },
                "Bias": { ipa: "/ˈbaɪ.əs/", meaning: "Thành kiến, thiên vị", paraphrase: "Prejudice in favor of or against one thing", type: "noun" },
                "Bulk": { ipa: "/bʌlk/", meaning: "Phần lớn, số lượng lớn", paraphrase: "The mass or magnitude of something large", type: "noun" },
                "Coherent": { ipa: "/kəʊˈhɪə.rənt/", meaning: "Mạch lạc, chặt chẽ", paraphrase: "Logical and consistent", type: "adjective" },
                "Coincide": { ipa: "/ˌkəʊ.ɪnˈsaɪd/", meaning: "Trùng hợp", paraphrase: "Occur at or during the same time", type: "verb" },
                "Commodity": { ipa: "/kəˈmɒd.ə.ti/", meaning: "Hàng hóa", paraphrase: "A raw material or primary agricultural product", type: "noun" },
                "Compatible": { ipa: "/kəmˈpæt.ə.bəl/", meaning: "Tương thích", paraphrase: "Able to exist or occur together without conflict", type: "adjective" },
                "Compile": { ipa: "/kəmˈpaɪl/", meaning: "Biên soạn, thu thập", paraphrase: "Produce by assembling information from other sources", type: "verb" },
                "Complement": { ipa: "/ˈkɒm.plɪ.ment/", meaning: "Bổ sung", paraphrase: "A thing that completes or brings to perfection", type: "noun/verb" },
                "Conceive": { ipa: "/kənˈsiːv/", meaning: "Hình thành trong đầu", paraphrase: "Form or devise a plan or idea in the mind", type: "verb" },
                "Concurrent": { ipa: "/kənˈkʌr.ənt/", meaning: "Đồng thời", paraphrase: "Existing, happening, or done at the same time", type: "adjective" }
            },
            homework: {}
        },
        2: { 
            inclass: {}, 
            homework: {
                "petition": { ipa: "/pəˈtɪʃ.ən/", meaning: "đơn kiến nghị", paraphrase: "A formal written request", type: "noun" },
                "discontent": { ipa: "/ˌdɪs.kənˈtent/", meaning: "sự bất mãn", paraphrase: "A feeling of dissatisfaction", type: "noun" },
                "social unrest": { ipa: "/ˌsəʊ.ʃəl ʌnˈrest/", meaning: "bất ổn xã hội", paraphrase: "Widespread public dissatisfaction", type: "noun phrase" },
                "appalling": { ipa: "/əˈpɔː.lɪŋ/", meaning: "kinh khủng", paraphrase: "Causing shock or dismay", type: "adjective" },
                "suffrage": { ipa: "/ˈsʌf.rɪdʒ/", meaning: "quyền bầu cử", paraphrase: "The right to vote", type: "noun" },
                "trade union": { ipa: "/ˌtreɪd ˈjuː.njən/", meaning: "công đoàn", paraphrase: "Association of workers", type: "noun phrase" },
                "collapse": { ipa: "/kəˈlæps/", meaning: "sụp đổ", paraphrase: "To fall down suddenly", type: "verb" },
                "subsequent": { ipa: "/ˈsʌb.sɪ.kwənt/", meaning: "tiếp theo", paraphrase: "Coming after something", type: "adjective" },
                "disillusionment": { ipa: "/ˌdɪs.ɪˈluː.ʒən.mənt/", meaning: "vỡ mộng", paraphrase: "Feeling of disappointment", type: "noun" },
                "found": { ipa: "/faʊnd/", meaning: "thành lập", paraphrase: "To establish", type: "verb" },
                "reform parliament": { ipa: "/rɪˈfɔːm ˈpɑː.lɪə.mənt/", meaning: "quốc hội cải cách", paraphrase: "Legislative body focused on reform", type: "noun phrase" },
                "champion": { ipa: "/ˈtʃæm.pi.ən/", meaning: "ủng hộ, bảo vệ", paraphrase: "To support or fight for", type: "verb" },
                "key figure": { ipa: "/kiː ˈfɪɡ.ər/", meaning: "nhân vật chủ chốt", paraphrase: "Important person", type: "noun phrase" },
                "delegate": { ipa: "/ˈdel.ɪ.ɡət/", meaning: "đại biểu", paraphrase: "Authorized representative", type: "noun" },
                "proclaim": { ipa: "/prəˈkleɪm/", meaning: "tuyên bố", paraphrase: "To announce officially", type: "verb" },
                "sacred": { ipa: "/ˈseɪ.krɪd/", meaning: "thiêng liêng", paraphrase: "Connected with God", type: "adjective" },
                "dismiss": { ipa: "/dɪsˈmɪs/", meaning: "bác bỏ", paraphrase: "To reject or send away", type: "verb" },
                "troops": { ipa: "/truːps/", meaning: "quân đội", paraphrase: "Soldiers", type: "noun" },
                "miner": { ipa: "/ˈmaɪ.nər/", meaning: "thợ mỏ", paraphrase: "Person working in a mine", type: "noun" },
                "crush": { ipa: "/krʌʃ/", meaning: "đàn áp", paraphrase: "To defeat completely", type: "verb" },
                "riot": { ipa: "/ˈraɪ.ət/", meaning: "bạo loạn", paraphrase: "Violent disturbance", type: "noun" },
                "abandon": { ipa: "/əˈbæn.dən/", meaning: "từ bỏ", paraphrase: "To give up completely", type: "verb" },
                "the cause": { ipa: "/ðə kɔːz/", meaning: "sự nghiệp", paraphrase: "A principle to fight for", type: "noun phrase" },
                "prominence": { ipa: "/ˈprɒm.ɪ.nəns/", meaning: "nổi bật", paraphrase: "State of being important", type: "noun" },
                "procession": { ipa: "/prəˈseʃ.ən/", meaning: "diễu hành", paraphrase: "Orderly movement of people", type: "noun" },
                "take precaution": { ipa: "/teɪk prɪˈkɔː.ʃən/", meaning: "đề phòng", paraphrase: "To act to prevent danger", type: "verb phrase" },
                "discredit": { ipa: "/dɪˈskred.ɪt/", meaning: "làm mất uy tín", paraphrase: "To harm reputation", type: "verb" },
                "fiasco": { ipa: "/fiˈæs.kəʊ/", meaning: "thất bại thảm hại", paraphrase: "Complete failure", type: "noun" },
                "abolition": { ipa: "/ˌæb.əˈlɪʃ.ən/", meaning: "bãi bỏ", paraphrase: "Act of ending something", type: "noun" },
                "far ahead of the times": { ipa: "/fɑːr əˈhed əv ðə taɪmz/", meaning: "vượt thời đại", paraphrase: "Too advanced for current era", type: "phrase" },
                "resolute action": { ipa: "/ˈrez.ə.luːt ˈæk.ʃən/", meaning: "hành động kiên quyết", paraphrase: "Firm measures", type: "noun phrase" },
                "suppress": { ipa: "/səˈpres/", meaning: "đàn áp", paraphrase: "To forcibly put an end to", type: "verb" },
                "rejection": { ipa: "/rɪˈdʒek.ʃən/", meaning: "từ chối", paraphrase: "Act of refusing", type: "noun" },
                "radical": { ipa: "/ˈræd.ɪ.kəl/", meaning: "cấp tiến", paraphrase: "Fundamental change", type: "adjective" },
                "austerity measures": { ipa: "/ɒˈster.ə.ti ˈmeʒ.əz/", meaning: "thắt lưng buộc bụng", paraphrase: "Spending cuts", type: "noun phrase" },
                "slash": { ipa: "/slæʃ/", meaning: "cắt giảm", paraphrase: "To reduce drastically", type: "verb" },
                "hike tax": { ipa: "/haɪk tæks/", meaning: "tăng thuế", paraphrase: "To increase taxes", type: "verb phrase" },
                "impose": { ipa: "/ɪmˈpəʊz/", meaning: "áp đặt", paraphrase: "To force acceptance", type: "verb" },
                "deficit": { ipa: "/ˈdef.ɪ.sɪt/", meaning: "thâm hụt", paraphrase: "Shortfall", type: "noun" },
                "unsustainable": { ipa: "/ˌʌn.səsˈteɪ.nə.bəl/", meaning: "không bền vững", paraphrase: "Cannot be maintained", type: "adjective" },
                "roll over current loans": { ipa: "/rəʊl ˈəʊ.və ˈkʌr.ənt ləʊnz/", meaning: "gia hạn vay", paraphrase: "Extend loan terms", type: "verb phrase" },
                "interest rate": { ipa: "/ˈɪn.trəst reɪt/", meaning: "lãi suất", paraphrase: "Loan interest percentage", type: "noun phrase" },
                "curtail": { ipa: "/kɜːˈteɪl/", meaning: "cắt giảm", paraphrase: "To reduce", type: "verb" },
                "elevate": { ipa: "/ˈel.ɪ.veɪt/", meaning: "nâng cao", paraphrase: "To raise up", type: "verb" },
                "excise": { ipa: "/ˈek.saɪz/", meaning: "thuế tiêu thụ", paraphrase: "Tax on goods", type: "noun" },
                "narrow": { ipa: "/ˈnær.əʊ/", meaning: "thu hẹp", paraphrase: "To make less wide", type: "verb" },
                "allowance": { ipa: "/əˈlaʊ.əns/", meaning: "phụ cấp", paraphrase: "Amount given", type: "noun" },
                "succession": { ipa: "/səkˈseʃ.ən/", meaning: "kế tiếp", paraphrase: "Sequence", type: "noun" },
                "indict": { ipa: "/ɪnˈdaɪt/", meaning: "truy tố", paraphrase: "To formally accuse", type: "verb" },
                "crisis": { ipa: "/ˈkraɪ.sɪs/", meaning: "khủng hoảng", paraphrase: "Time of danger", type: "noun" },
                "soar": { ipa: "/sɔːr/", meaning: "tăng vọt", paraphrase: "To increase rapidly", type: "verb" },
                "turn sour": { ipa: "/tɜːn ˈsaʊər/", meaning: "trở nên xấu", paraphrase: "To become bad", type: "verb phrase" },
                "retract": { ipa: "/rɪˈtrækt/", meaning: "rút lại", paraphrase: "To withdraw", type: "verb" },
                "decimate": { ipa: "/ˈdes.ɪ.meɪt/", meaning: "tàn phá", paraphrase: "To destroy large part", type: "verb" },
                "out of work": { ipa: "/aʊt əv wɜːk/", meaning: "thất nghiệp", paraphrase: "Unemployed", type: "adjective phrase" },
                "implement": { ipa: "/ˈɪm.plɪ.ment/", meaning: "thực thi", paraphrase: "To put into effect", type: "verb" },
                "slump": { ipa: "/slʌmp/", meaning: "sụt giảm", paraphrase: "Severe fall", type: "noun" },
                "denounce": { ipa: "/dɪˈnaʊns/", meaning: "lên án", paraphrase: "To condemn publicly", type: "verb" },
                "frivolity": { ipa: "/frɪˈvɒl.ə.ti/", meaning: "phù phiếm", paraphrase: "Lack of seriousness", type: "noun" },
                "ratchet up": { ipa: "/ˈrætʃ.ɪt ʌp/", meaning: "tăng dần", paraphrase: "To increase gradually", type: "verb phrase" },
                "contract": { ipa: "/kənˈtrækt/", meaning: "co lại", paraphrase: "To decrease in size", type: "verb" }
            }
        },
        3: { inclass: {}, homework: {} },
        4: { inclass: {}, homework: {} },
        5: { inclass: {}, homework: {} },
        6: { inclass: {}, homework: {} },
        7: { 
            inclass: {},
            homework: {
                "Professional Strangers": {
                    "Anthropology": { ipa: "/ˌæn.θrəˈpɒl.ə.dʒi/", meaning: "Nhân chủng học", paraphrase: "She studied anthropology to understand different cultures around the world.", type: "noun", paragraph: "A" },
                    "Scholarly": { ipa: "/ˈskɒl.ə.li/", meaning: "Học thuật, uyên bác", paraphrase: "The professor published several scholarly articles in prestigious journals.", type: "adjective", paragraph: "A" },
                    "Whet sb appetite": { ipa: "/wet ˈæp.ɪ.taɪt/", meaning: "Kích thích sự thèm muốn", paraphrase: "The preview really whetted my appetite for the full documentary.", type: "phrase", paragraph: "A" },
                    "Doggedly": { ipa: "/ˈdɒɡ.ɪd.li/", meaning: "Bền bỉ, kiên trì", paraphrase: "Despite many rejections, she doggedly pursued her research goals.", type: "adverb", paragraph: "A" },
                    "Preface": { ipa: "/ˈpref.əs/", meaning: "Lời nói đầu, lời tựa", paraphrase: "The author's preface explained the inspiration behind the book.", type: "noun", paragraph: "A" },
                    "Accounts": { ipa: "/əˈkaʊnts/", meaning: "Tường thuật, câu chuyện", paraphrase: "Historians rely on first-hand accounts to understand past events.", type: "noun", paragraph: "A" },
                    "Purist": { ipa: "/ˈpjʊə.rɪst/", meaning: "Người theo chủ nghĩa thuần túy", paraphrase: "As a language purist, he refused to use modern slang in his writing.", type: "noun", paragraph: "B" },
                    "Elicit": { ipa: "/ɪˈlɪs.ɪt/", meaning: "Gợi ra, moi ra, khơi gợi", paraphrase: "The interviewer tried to elicit honest responses from the participants.", type: "verb", paragraph: "B" },
                    "Fieldwork": { ipa: "/ˈfiːld.wɜːk/", meaning: "Nghiên cứu thực địa", paraphrase: "The anthropologist spent two years doing fieldwork in remote villages.", type: "noun", paragraph: "C" },
                    "Reticent": { ipa: "/ˈret.ɪ.sənt/", meaning: "Kín đáo, dè dặt", paraphrase: "She was reticent about sharing details of her personal life.", type: "adjective", paragraph: "C" },
                    "Ethical": { ipa: "/ˈeθ.ɪ.kəl/", meaning: "Có đạo đức, thuộc về đạo đức", paraphrase: "Researchers must follow ethical guidelines when working with human subjects.", type: "adjective", paragraph: "C" },
                    "Attire": { ipa: "/əˈtaɪər/", meaning: "Mặc quần áo chỉnh tề", paraphrase: "Guests were asked to attire themselves in formal evening wear.", type: "verb", paragraph: "D" },
                    "Vouch for": { ipa: "/vaʊtʃ fɔːr/", meaning: "Bảo đảm cho, xác nhận", paraphrase: "I can vouch for her reliability as she has never let me down.", type: "phrasal verb", paragraph: "E" },
                    "Disclose": { ipa: "/dɪˈskləʊz/", meaning: "Tiết lộ, công khai", paraphrase: "The company refused to disclose details about the new product launch.", type: "verb", paragraph: "E" },
                    "Matter-of-fact manner": { ipa: "/ˌmæt.ər.əvˈfækt ˈmæn.ər/", meaning: "Thái độ thực tế, không cảm xúc", paraphrase: "She delivered the bad news in a matter-of-fact manner without emotion.", type: "phrase", paragraph: "G" },
                    "Clam up": { ipa: "/klæm ʌp/", meaning: "Im bặt, câm như hến", paraphrase: "Whenever the topic of money comes up, he clams up immediately.", type: "phrasal verb", paragraph: "G" },
                    "Curiosity": { ipa: "/ˌkjʊə.riˈɒs.ə.ti/", meaning: "Sự tò mò, tính hiếu kỳ", paraphrase: "Scientific curiosity drives researchers to explore the unknown.", type: "noun", paragraph: "G" },
                    "Contradict": { ipa: "/ˌkɒn.trəˈdɪkt/", meaning: "Mâu thuẫn, trái ngược", paraphrase: "The witness's statement contradicted earlier police reports.", type: "verb", paragraph: "H" },
                    "Misconception": { ipa: "/ˌmɪs.kənˈsep.ʃən/", meaning: "Sự hiểu lầm", paraphrase: "There's a common misconception that all snakes are poisonous.", type: "noun", paragraph: "H" },
                    "Outline": { ipa: "/ˈaʊt.laɪn/", meaning: "Dàn ý, phác thảo", paraphrase: "The teacher asked students to create an outline before writing their essays.", type: "noun", paragraph: "H" }
                },
                "A New Planet": {
                    "Extra-terrestrial life": { ipa: "/ˌek.strə.təˈres.tri.əl laɪf/", meaning: "Sự sống ngoài Trái Đất", paraphrase: "Scientists continue searching for evidence of extra-terrestrial life in our solar system.", type: "noun phrase", paragraph: "A" },
                    "Astronomers": { ipa: "/əˈstrɒn.ə.mərz/", meaning: "Các nhà thiên văn học", paraphrase: "Astronomers discovered a new galaxy using advanced telescopes.", type: "noun", paragraph: "A" },
                    "Criterion": { ipa: "/kraɪˈtɪə.ri.ən/", meaning: "Tiêu chí", paraphrase: "The main criterion for selection is academic excellence.", type: "noun", paragraph: "A" },
                    "Organism": { ipa: "/ˈɔː.ɡən.ɪ.zəm/", meaning: "Sinh vật", paraphrase: "This microscopic organism can survive in extreme conditions.", type: "noun", paragraph: "A" },
                    "Harbour": { ipa: "/ˈhɑː.bər/", meaning: "Chứa đựng, che chở", paraphrase: "The cave may harbour unique species yet to be discovered.", type: "verb", paragraph: "A" },
                    "Formation": { ipa: "/fɔːˈmeɪ.ʃən/", meaning: "Sự hình thành", paraphrase: "The formation of planets takes millions of years.", type: "noun", paragraph: "A" },
                    "Habitable zone": { ipa: "/ˈhæb.ɪ.tə.bəl zəʊn/", meaning: "Vùng có thể sống được", paraphrase: "The planet orbits within the star's habitable zone where water could exist.", type: "noun phrase", paragraph: "B" },
                    "Toehold": { ipa: "/ˈtəʊ.həʊld/", meaning: "Chỗ đứng, chỗ bám vững chắc", paraphrase: "The company gained a toehold in the Asian market last year.", type: "noun", paragraph: "B" },
                    "Exude": { ipa: "/ɪɡˈzjuːd/", meaning: "Tiết ra, tỏa ra", paraphrase: "The plant exudes a sweet fragrance that attracts insects.", type: "verb", paragraph: "C" },
                    "Boast": { ipa: "/bəʊst/", meaning: "Sở hữu, với sự tự hào", paraphrase: "The hotel boasts panoramic views of the ocean.", type: "verb", paragraph: "D" },
                    "Precision": { ipa: "/prɪˈsɪʒ.ən/", meaning: "Độ chính xác", paraphrase: "The surgery requires extreme precision and careful attention.", type: "noun", paragraph: "D" },
                    "Be amenable to": { ipa: "/bi əˈmiː.nə.bəl tuː/", meaning: "Dễ bị tác động", paraphrase: "The committee was amenable to suggestions from the public.", type: "phrase", paragraph: "E" },
                    "Light spectrum": { ipa: "/laɪt ˈspek.trəm/", meaning: "Quang phổ ánh sáng", paraphrase: "Scientists analyze the light spectrum to determine a star's composition.", type: "noun phrase", paragraph: "E" },
                    "Vessel": { ipa: "/ˈves.əl/", meaning: "Tàu, thuyền; mạch máu; vật chứa", paraphrase: "The research vessel departed for a three-month expedition.", type: "noun", paragraph: "E" },
                    "Molecule": { ipa: "/ˈmɒl.ɪ.kjuːl/", meaning: "Phân tử", paraphrase: "Water is composed of molecules containing hydrogen and oxygen.", type: "noun", paragraph: "E" },
                    "Glare": { ipa: "/ɡleər/", meaning: "Ánh sáng chói, chói lóa", paraphrase: "The glare from the sun made it difficult to see the road.", type: "noun", paragraph: "E" }
                },
                "Male Body": {
                    "Prevailing": { ipa: "/prɪˈveɪ.lɪŋ/", meaning: "Phổ biến, thịnh hành", paraphrase: "The prevailing opinion is that technology improves our lives.", type: "adjective", paragraph: "A" },
                    "Notion": { ipa: "/ˈnəʊ.ʃən/", meaning: "Quan niệm, ý kiến", paraphrase: "She had the notion that success would come easily.", type: "noun", paragraph: "A" },
                    "Static": { ipa: "/ˈstæt.ɪk/", meaning: "Tĩnh, không thay đổi", paraphrase: "The economy remained static despite government intervention.", type: "adjective", paragraph: "A" },
                    "Silhouette": { ipa: "/ˌsɪl.uˈet/", meaning: "Hình bóng, bóng dáng", paraphrase: "We could see the silhouette of the mountains against the sunset.", type: "noun", paragraph: "B" },
                    "Slender": { ipa: "/ˈslen.dər/", meaning: "Mảnh khảnh, thon thả", paraphrase: "The dancer had a slender and graceful figure.", type: "adjective", paragraph: "B" },
                    "Edgy": { ipa: "/ˈedʒ.i/", meaning: "Gai góc, khác biệt", paraphrase: "The designer's edgy clothing style appeals to young urbanites.", type: "adjective", paragraph: "B" },
                    "Androgynous": { ipa: "/ænˈdrɒdʒ.ɪ.nəs/", meaning: "Phi giới tính", paraphrase: "The model's androgynous look challenges traditional gender norms.", type: "adjective", paragraph: "B" },
                    "Towering": { ipa: "/ˈtaʊə.rɪŋ/", meaning: "Cao lớn", paraphrase: "The towering skyscrapers dominated the city skyline.", type: "adjective", paragraph: "B" },
                    "Squeeze out": { ipa: "/skwiːz aʊt/", meaning: "Ép ra, vắt kiệt", paraphrase: "Large corporations often squeeze out smaller competitors from the market.", type: "phrasal verb", paragraph: "C" },
                    "Trouser": { ipa: "/ˈtraʊ.zər/", meaning: "Quần tây", paraphrase: "He bought a new pair of trousers for the job interview.", type: "noun", paragraph: "C" },
                    "Waistline": { ipa: "/ˈweɪst.laɪn/", meaning: "Vòng eo", paraphrase: "Regular exercise can help reduce your waistline significantly.", type: "noun", paragraph: "C" },
                    "Physique": { ipa: "/fɪˈziːk/", meaning: "Thể chất, vóc dáng", paraphrase: "Athletes train for years to develop their impressive physique.", type: "noun", paragraph: "C" },
                    "Go to great lengths to": { ipa: "/ɡəʊ tə ɡreɪt leŋθs tuː/", meaning: "Dùng nhiều công sức", paraphrase: "Parents will go to great lengths to ensure their children's safety.", type: "phrase", paragraph: "D" },
                    "Surgical": { ipa: "/ˈsɜː.dʒɪ.kəl/", meaning: "Thuộc về phẫu thuật", paraphrase: "The patient required surgical intervention to repair the damaged tissue.", type: "adjective", paragraph: "D" },
                    "Liposuction": { ipa: "/ˈlɪp.əʊˌsʌk.ʃən/", meaning: "Hút mỡ", paraphrase: "He considered liposuction as a quick solution for weight loss.", type: "noun", paragraph: "D" },
                    "Eating disorder": { ipa: "/ˈiː.tɪŋ dɪˌsɔː.dər/", meaning: "Rối loạn ăn uống", paraphrase: "Anorexia is a serious eating disorder that requires professional treatment.", type: "noun phrase", paragraph: "E" },
                    "Binge": { ipa: "/bɪndʒ/", meaning: "Làm điều gì đó quá mức, không kiểm soát", paraphrase: "After the diet ended, she would binge on junk food every weekend.", type: "verb", paragraph: "E" },
                    "Induce": { ipa: "/ɪnˈdjuːs/", meaning: "Gây ra, xui khiến", paraphrase: "Stress can induce physical symptoms like headaches and fatigue.", type: "verb", paragraph: "E" },
                    "Vomit": { ipa: "/ˈvɒm.ɪt/", meaning: "Nôn mửa", paraphrase: "The food poisoning caused him to vomit throughout the night.", type: "verb", paragraph: "E" },
                    "Afflict": { ipa: "/əˈflɪkt/", meaning: "Ảnh hưởng tiêu cực", paraphrase: "Poverty continues to afflict millions of people worldwide.", type: "verb", paragraph: "E" },
                    "Thrust": { ipa: "/θrʌst/", meaning: "Đẩy, nhét mạnh", paraphrase: "She thrust the letter into his hands and walked away.", type: "verb", paragraph: "E" },
                    "Bulimia": { ipa: "/buːˈlɪm.i.ə/", meaning: "Chứng cuồng ăn, sau đó nôn ra để không bị tăng cân", paraphrase: "People with bulimia often struggle with cycles of bingeing and purging.", type: "noun", paragraph: "E" },
                    "Complement": { ipa: "/ˈkɒm.plɪ.ment/", meaning: "Bổ sung, làm đầy đủ", paraphrase: "The red wine perfectly complements the grilled steak.", type: "verb", paragraph: "F" },
                    "Displace": { ipa: "/dɪˈspleɪs/", meaning: "Thay thế, di dời", paraphrase: "Digital cameras have displaced traditional film cameras in most markets.", type: "verb", paragraph: "F" },
                    "Recession": { ipa: "/rɪˈseʃ.ən/", meaning: "Suy thoái kinh tế", paraphrase: "The country entered a severe recession following the financial crisis.", type: "noun", paragraph: "F" },
                    "Masculine": { ipa: "/ˈmæs.kjə.lɪn/", meaning: "Nam tính", paraphrase: "Society often associates certain traits with masculine behavior.", type: "adjective", paragraph: "F" },
                    "Fall out of favor": { ipa: "/fɔːl aʊt əv ˈfeɪ.vər/", meaning: "Không còn được ưa chuộng", paraphrase: "Traditional teaching methods have fallen out of favor with modern educators.", type: "phrase", paragraph: "F" },
                    "Weather": { ipa: "/ˈweð.ər/", meaning: "Vượt qua, chịu đựng", paraphrase: "The company managed to weather the economic storm successfully.", type: "verb", paragraph: "F" },
                    "Flounder": { ipa: "/ˈflaʊn.dər/", meaning: "Vật lộn, lúng túng", paraphrase: "Without clear direction, the project began to flounder after six months.", type: "verb", paragraph: "F" },
                    "Correlation": { ipa: "/ˌkɒr.əˈleɪ.ʃən/", meaning: "Sự tương quan", paraphrase: "Researchers found a strong correlation between exercise and mental health.", type: "noun", paragraph: "F" },
                    "Effeminacy": { ipa: "/ɪˈfem.ɪ.nə.si/", meaning: "Sự ẻo lả, nữ tính", paraphrase: "Historical attitudes toward effeminacy in men have evolved significantly.", type: "noun", paragraph: "F" },
                    "Pronounced": { ipa: "/prəˈnaʊnst/", meaning: "Rõ rệt, dễ thấy", paraphrase: "There was a pronounced difference in quality between the two products.", type: "adjective", paragraph: "F" },
                    "Polarized ideas": { ipa: "/ˈpəʊ.lə.raɪzd aɪˈdɪəz/", meaning: "Những ý kiến phân cực", paraphrase: "The debate featured polarized ideas about climate change policy.", type: "noun phrase", paragraph: "G" },
                    "Columnist": { ipa: "/ˈkɒl.əm.nɪst/", meaning: "Người viết chuyên mục", paraphrase: "The newspaper columnist writes about political issues every Sunday.", type: "noun", paragraph: "G" },
                    "Exude": { ipa: "/ɪɡˈzjuːd/", meaning: "Tiết ra, tỏa ra", paraphrase: "The successful CEO exudes confidence in every business meeting.", type: "verb", paragraph: "G" },
                    "Destabilize": { ipa: "/diːˈsteɪ.bɪ.laɪz/", meaning: "Gây bất ổn", paraphrase: "The scandal threatened to destabilize the entire government.", type: "verb", paragraph: "G" },
                    "Futile": { ipa: "/ˈfjuː.taɪl/", meaning: "Vô nghĩa", paraphrase: "All attempts to rescue the trapped miners proved futile in the end.", type: "adjective", paragraph: "H" }
                }
            }
        }
    },
    listening: {
        1: { inclass: {}, homework: {} },
        2: { inclass: {}, homework: {} },
        3: { inclass: {}, homework: {} },
        4: { inclass: {}, homework: {} },
        5: { inclass: {}, homework: {} },
        6: { 
            inclass: {},
            homework: {
                "Straightforward": { ipa: "/ˌstreɪtˈfɔː.wəd/", meaning: "Thẳng thắn, dễ hiểu", paraphrase: "Easy to understand or simple", type: "adjective" },
                "Collate": { ipa: "/kəˈleɪt/", meaning: "Thu thập và sắp xếp", paraphrase: "Collect and arrange in proper order", type: "verb" },
                "Exhibit": { ipa: "/ɪɡˈzɪb.ɪt/", meaning: "Trưng bày", paraphrase: "Display or show publicly", type: "verb" },
                "Get sth out of the way": { ipa: "/ɡet aʊt əv ðə weɪ/", meaning: "Xử lý xong cái gì đó", paraphrase: "Complete or deal with something so it's no longer a concern", type: "phrase" },
                "Order of importance": { ipa: "/ˈɔː.dər əv ɪmˈpɔː.təns/", meaning: "Thứ tự ưu tiên", paraphrase: "Sequence based on how important things are", type: "phrase" },
                "First-hand experience": { ipa: "/ˌfɜːst ˈhænd ɪkˈspɪə.ri.əns/", meaning: "Kinh nghiệm thực tế", paraphrase: "Direct personal experience, not from others", type: "phrase" },
                "Background reading": { ipa: "/ˈbæk.ɡraʊnd ˈriː.dɪŋ/", meaning: "Đọc kiến thức nền", paraphrase: "Reading to gain foundational knowledge on a topic", type: "phrase" },
                "Settle in": { ipa: "/ˈset.əl ɪn/", meaning: "Làm quen, ổn định", paraphrase: "Become comfortable in a new situation", type: "phrasal verb" },
                "Make sense": { ipa: "/meɪk sens/", meaning: "Có lí, hợp lý", paraphrase: "Be logical or understandable", type: "phrase" },
                "Legible": { ipa: "/ˈledʒ.ə.bəl/", meaning: "Chữ rõ ràng, dễ đọc", paraphrase: "Clear enough to read", type: "adjective" },
                "Jot down": { ipa: "/dʒɒt daʊn/", meaning: "Ghi chép nhanh", paraphrase: "Write something quickly", type: "phrasal verb" },
                "Laboratory": { ipa: "/ləˈbɒr.ə.tər.i/", meaning: "Phòng thí nghiệm", paraphrase: "Room for scientific experiments and research", type: "noun" },
                "Theory": { ipa: "/ˈθɪə.ri/", meaning: "Lý thuyết, học thuyết", paraphrase: "Set of principles explaining something", type: "noun" },
                "Abide by": { ipa: "/əˈbaɪd baɪ/", meaning: "Tuân theo, chấp hành", paraphrase: "Follow or obey rules", type: "phrasal verb" },
                "Procedures": { ipa: "/prəˈsiː.dʒərz/", meaning: "Quy trình, thủ tục", paraphrase: "Established way of doing something", type: "noun" },
                "Safety glasses": { ipa: "/ˈseɪf.ti ɡlæs.ɪz/", meaning: "Kính bảo hộ", paraphrase: "Protective eyewear for safety", type: "noun" },
                "Goggles": { ipa: "/ˈɡɒɡ.əlz/", meaning: "Kính bảo hộ (ôm sát mặt)", paraphrase: "Close-fitting protective glasses", type: "noun" },
                "Hazard": { ipa: "/ˈhæz.əd/", meaning: "Mối nguy hiểm", paraphrase: "Source of danger", type: "noun" },
                "Trainers": { ipa: "/ˈtreɪ.nərz/", meaning: "Giày thể thao", paraphrase: "Athletic or sports shoes", type: "noun" },
                "Thorough": { ipa: "/ˈθʌr.ə/", meaning: "Kỹ lưỡng, tỉ mỉ", paraphrase: "Complete and careful", type: "adjective" }
            }
        },
        7: { inclass: {}, homework: {} },
        8: { inclass: {}, homework: {} }
    }
};
